### ISSUE TITLE
Cube Overview Image not being able to be set

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1002]
You can't copy/paste you have to use the autocomplete

**Comment by ibanner56** [comment]
To add to this, I can change the picture on a cube I made more recently, but not an older cube:

changes:
https://cubecobra.com/cube/overview/speedmetal

doesn't change: 
https://cubecobra.com/cube/overview/dolladolla

**Comment by thyeggman** [comment]
My cube also has this problem:

https://cubecobra.com/cube/overview/1oo

**Comment by dekkerglen** [comment]
Is this the copy/paste issue or something else?

**Comment by thyeggman** [comment]
Oh, it's not that.  The title is actually the exact issue, but the description appears to be a different one.  When I change the image, save, and then go back to the "Edit Overview" page, the field is saved, but the image is not updated.

**Comment by dekkerglen** [comment]
And this is with clicking on the drop-down item?

**Comment by thyeggman** [comment]
Yes, I start typing the name of the card art I would like to use, then select the one from the drop down, and click save.  I still see the above behavior

**Comment by dekkerglen** [comment]
issue is the input needs to be all lowercase.
