### ISSUE TITLE
Add the option to sort cards by name

### ISSUE THREAD

**Issue by klaffke** [dekkerglen/CubeCobra#1007]
**What would you like to be able to do?**
Alphabetically sorting the cards of a cube 

**Describe how you would use the feature**
The "Primary Sort" and "Secondary Sort" lists do not seem to provide an option to sort by card name. "Name" would be a welcome addition to the myriad of other sort options already present.

**Comment by dekkerglen** [comment]
Alphabetic sort is the default tertiary sort. Alphabetic sort doesn't work with our table sort, as everything needs to be put into 'buckets'.

**Comment by klaffke** [comment]
Thanks fo the clarification. Setting primary/secondary sort to "unsorted" does the trick.
