### ISSUE TITLE
Cube Tags always reset to blank

### ISSUE THREAD

**Issue by ghost** [dekkerglen/CubeCobra#1009]
**Describe the bug**
When I clear the tags from my cube and add new ones, they appear in the overview when I save them, but get cleared to empty once I refresh the page.  My cube is older and this bug may not affect all cubes.

**To Reproduce**
1. In the "Edit Overview" panel, clear all the tags from the cube (don't know that this is necessary, but it gives a normalized starting point).
2. Add one or more tags.
3. Save the changes.
4. Observe that the tags appear underneath the cube description.
5. Refresh the page.
6. Observe that the same number of tags are still present, but now are empty.

**Expected behavior**
I want the tags to actually be saved.

**Screenshots**
Starting state (some empty tags):
![image](https://user-images.githubusercontent.com/13246299/73680252-cc887d80-4670-11ea-9889-ad12ada62c55.png)

Tags added:
![image](https://user-images.githubusercontent.com/13246299/73680309-e033e400-4670-11ea-832f-84a318b82181.png)

New overview:
![image](https://user-images.githubusercontent.com/13246299/73680346-ea55e280-4670-11ea-872b-7875dce2572c.png)

After refresh go back to the first image.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  77.0.3865.120 (Official Build) (64-bit)

**Additional context**
My cube is a bit older and after talking with others there seem to be issues with cubes created a while ago cropping up.  Not sure if that applies to this particular bug.

Cube links (not sure which one is the "right" one but depending on where I navigate from I get a different link):

https://cubecobra.com/cube/overview/5d8414f0bc8ca26a5729598c
https://cubecobra.com/cube/overview/1oo

**Comment by ibanner56** [comment]
I was able to repro this for my cubes as well.

**Comment by thyeggman** [comment]
FYI the original poster here was me, I just deleted that account and merged it with this one.

**Comment by thyeggman** [comment]
@dekkerglen This bug still exists for my cube, the behavior is slightly different though.  There's no before/after refresh difference anymore (with some blank tags and some filled out), they all just appear as empty tags.  When I go back to the overview, the same number of tags still exist, but they're empty.
