### ISSUE TITLE
Add a Note field to cards

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1011]
**What would you like to be able to do?**
Have a large freeform text field to make notes about a card in my cube.

**Describe how you would use the feature**
Note reasons for inclusion, indicators of past performance, general thoughts, and credits to the artists who did alters.

**Additional context**
Suggested by mauriciopasquier on discord.

**Comment by mauriciopasquier** [comment]
It would be awesome to have these notes as a tooltip on each card, while drafting. That way I can tell new drafters about possible archetypes for a card, or things like packages ("This comes with 3 more Squadron Hawks"), what is the drafted booster for Booster Tutor, etc.

**Comment by dekkerglen** [comment]
Not sure I like having these as tooltips during draft. That feels like a separate feature.

**Comment by ThijsHoenjet** [comment]
I would like to propose another way of doing this: Add multiple key value fields to each card.
How it works:
As default their is a key field filled with "Description" and an empty field next to it to enter text for the description.
Then there is also a + button below that, that will add another key and value field to the form.
This way you can organize any data you want per card in a structured way, while not complicating things for people that just want a description field as that is there by default.
