### ISSUE TITLE
Decrease P1P1 image size

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1018]
Discord upload image is 8mb, so if we go just under that, it will be easier to copy+paste images into discord. We're currently just above 8mb on average.

**Comment by timfreilly** [comment]
Do you think it's better to do this by making the image smaller or by compressing it more?

**Comment by dekkerglen** [comment]
Either works

**Comment by lane-eden** [comment]
Fixed in #1277
