### ISSUE TITLE
Add/Remove Cards Save Changes Error

### ISSUE THREAD

**Issue by jamesriley72281** [dekkerglen/CubeCobra#102]
**Describe the bug**
When trying to Add/Remove card(s) to a cube the 'Save Changes' button causes an error. See pastebin link below for error. 

**Pastebin:** https://pastebin.com/VnKV95sH

**To Reproduce**
1. Got to List > Add/Remove
2. Search for a card and click 'Just Add'
3. Click 'Save Changes'

**Expected behavior**
Changes are saved, default List view is loaded and confirmation prompt/cards added is seen

**Screenshots**
N/A screen just displays the pastebin contents linked above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version latest build

**Comment by lane-eden** [comment]
Fixed in PR #105
