### ISSUE TITLE
Edit Cube Overview Save Button Unresponsive

### ISSUE THREAD

**Issue by jamesriley72281** [dekkerglen/CubeCobra#103]
**Describe the bug**
When editing the Cube Overview of a cube the `Save` button is unresponsive on click. Nothing is showing in the console.

Could be related to recent changes here https://github.com/dekkerglen/CubeCobra/commit/affc6d5

**To Reproduce**
1. Go to Cube Overview
2. Click `Edit Overview`
3. Make changes to the overview if you'd like
4. Click `Save` button

**Expected behavior**
Changes will be saved and user is taken back to Cube Overview page

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Latest Build

**Comment by lane-eden** [comment]
Fixed in #109
