### ISSUE TITLE
Color Category Override

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1081]
As a user, I would like a color category override to better sort.

It should be a dropdown with the following Options:

- White
- Blue
- Black
- Red
- Green
- Colorless
- Multicolored
- Land
- Hybrid

Also add 'Hybrid' as a color category

Sorts/filter would need to be updated to grab the override field correctly

**Comment by lane-eden** [comment]
Addressed in #1283
