### ISSUE TITLE
Card page meta data

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1083]
Currently, card page meta data doesn't have any contextual information. It should have the card image and card name displayed when you share the links on discord etc. Similar to how cube metadata works.

Current:
![Screenshot_20200216-160628_Discord](https://user-images.githubusercontent.com/28238025/74612772-71c23d80-50d6-11ea-8125-88715923dbff.jpg)

**Comment by gabyreilly** [comment]
I can pick up this one!
