### ISSUE TITLE
Safari going into error state

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1091]
This screenshot was sent to me, saying all cubes do this on safari on mobile:

![image](https://user-images.githubusercontent.com/28238025/74659559-94019d00-5162-11ea-9d14-ffe518e5de41.png)

**Comment by dekkerglen** [comment]
Update:
Some pages working fine:
![image](https://user-images.githubusercontent.com/28238025/74660569-5998ff80-5164-11ea-8f4f-0f32292de157.png)
![image](https://user-images.githubusercontent.com/28238025/74660585-60277700-5164-11ea-8024-d0f9183a55bd.png)

But starting a draft gets 400'd:
![image](https://user-images.githubusercontent.com/28238025/74660602-6cabcf80-5164-11ea-9a52-f243f1e92aab.png)

**Comment by dekkerglen** [comment]
User reported they were not logged in at the time

**Comment by phulin** [comment]
Did the user report a version

**Comment by dekkerglen** [comment]
Followed up with user, they were using safari 13.3.1
