### ISSUE TITLE
Confirm Bulk Import not showing login state

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1092]
This was reported:

This is not possible due to this screen only being accessible when logged in. The user reported that after finishing the import, the user was logged in correctly.

![image](https://user-images.githubusercontent.com/28238025/74660313-e55e5c00-5163-11ea-8ae6-03b8d35b16f5.png)

**Comment by gabyreilly** [comment]
I'll pick this one up.

It seems like quite a bit of data is missing from this page's state-- when you get into this state, the "Overview", "List", etc menu considers the cube ID to be undefined as well.
