### ISSUE TITLE
Better Autogenerated Cube Overviews

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#110]
As a user, I would like the autogenerated one-liner to more nuanced and indicative of my cube.

First change is to define pauper as cards legal in pauper, and banned in pauper, so it will allow any card printed as common.
Second change is to allow overwriting of this tagline in cube overview. Use dropdowns and pre-determined values so users can't go too crazy.

**Comment by dekkerglen** [comment]
Make the 'banned' switch for modern as well.

**Comment by jamesriley72281** [comment]
We may want to include a prefix for {'', 'Powered','Unpowered'}

**Comment by dekkerglen** [comment]
Also include more formats scryfall doesn't provide that are common for cubes: peasant for example

**Comment by dekkerglen** [comment]
Add a new label: "Freeform" for cubes that contain cards that are banned, not restricted in vintage such as silver bordered cards.

**Comment by joshfinnie** [comment]
I'll take this one!

**Comment by dekkerglen** [comment]
Building override options for this
