### ISSUE TITLE
Cards that appear more than once in playtest mode can't be picked.

### ISSUE THREAD

**Issue by APillowEdwards** [dekkerglen/CubeCobra#1123]
**Describe the bug**
In playtest mode, multiples of the same card appearing in a pack result in neither being pickable due to a JS error:
`Util.js:83 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of null
    at d (Util.js:83)
    at CubeDraftPage.js:170
    at Object.Bi (react-dom.production.min.js:175)
    at Ai (react-dom.production.min.js:14)
    at Di (react-dom.production.min.js:14)
    at wf (react-dom.production.min.js:14)
    at Ei (react-dom.production.min.js:176)
    at zd (react-dom.production.min.js:15)
    at uc (react-dom.production.min.js:15)
    at aj (react-dom.production.min.js:41)`

**To Reproduce**
1. Go to [https://cubecobra.com/cube/draft/5e4e88db18368406b4324502](https://cubecobra.com/cube/draft/5e4e88db18368406b4324502)
2. Pick any card (I picked Grusilda) followed by either copy of Watermarket.

**Expected behavior**
Watermarket should be picked.

**Desktop (please complete the following information):**
 - OS: W10
 - Chrome 80.0.3987.106 (64-bit)

**Comment by APillowEdwards** [comment]
Having the same error on this draft too, but not with a duplicate card in a pack:
https://cubecobra.com/cube/draft/5e4eb722192a1a508a08d20e

I'm unable to pick Steam-Powered after these picks:
![image](https://user-images.githubusercontent.com/11028833/74958578-11e2d400-5401-11ea-8207-8c9f725b659d.png)

**Comment by gabyreilly** [comment]
Hi, I'm taking a look at this!

It looks like for both issues, it is failing because the CMC is `null`.  The code does not handle this gracefully, so it fails to pick them.

I am not sure if the CMC is null because of the way the cards were imported, or if you made some manual changes.

A temporary workaround would be to explicitly set their CMC to 0.  I'll look at making a long-term fix too.

**Comment by APillowEdwards** [comment]
When I imported from text it didn't bring in CMC nor color for some reason, which will be where the null CMC came from (I manually set the cards with mana costs).

Thanks for looking into this.

**Comment by gabyreilly** [comment]
@APillowEdwards thanks, that detail is helpful!

> When I imported from text it didn't bring in CMC nor color for some reason, which will be where the null CMC came from (I manually set the cards with mana costs).
> 
> Thanks for looking into this.

I opened a new ticket so we don't lose track of the import issue you described.  Could you attach the text file you used to https://github.com/dekkerglen/CubeCobra/issues/1136 ? thanks!
