### ISSUE TITLE
Devotion Field for Cards

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1130]
**What would you like to be able to do?**
A field that tells me the devotion/number of colored pips. This should be user overridable the same as cmc.

**Describe how you would use the feature**
Have analytics show devotion and look for cards with higher devotions for things like devotion matters themes.

**Additional context**
Have to determine if it should be per color or just total devotion and whether true colorless counts.

**Comment by dekkerglen** [comment]
We have a parsed_cost field in details. Can we use that to count devotion instead of making it an extremely niche field?

**Comment by ruler501** [comment]
Kind of but the regexes for it get really ugly if using it for filtering
(assuming we supported regexes).
