### ISSUE TITLE
Send notification when a cube I follow is updated

### ISSUE THREAD

**Issue by timfreilly** [dekkerglen/CubeCobra#1131]
From discord:
<img width="693" alt="Screen Shot 2020-02-20 at 3 16 10 PM" src="https://user-images.githubusercontent.com/1253274/74988912-f02f2000-53f3-11ea-85bd-f99fae64db96.png">

(should probably also do this not just when you're following a cube, but also when you're following a user that updates their cube)

**Comment by dekkerglen** [comment]
Are we going to talk about using light mode on discord?

**Comment by timfreilly** [comment]
@gabyreilly and I are working on this today.

**Comment by timfreilly** [comment]
This should probably trigger whenever a blog post is made, right?

Looking at the code there are four places in cube_routes where blog posts are saved. Is there any way I could consolidate that so I'm not writing the same/similar code in four places? What's a good way to organize that sort of thing in this project?

**Comment by timfreilly** [comment]
This notification is also new for this app in that it's sending a notification to several users at once. Rather than sending to a user, it's sending to all users that follow this cube or the owner of this cube.
