### ISSUE TITLE
Should we allow CMC to be removed from cards?

### ISSUE THREAD

**Issue by gabyreilly** [dekkerglen/CubeCobra#1133]
Follow up from issue https://github.com/dekkerglen/CubeCobra/issues/1123

In the edit modal and the bulk edit screen, I can delete the CMC of a card.  This saves it as `null` in the db.

Is this something we should allow? Is it something that is desired by players? is `null` useful in some way?

If not, we should ensure the inputs are stricter and avoid these kind of issues in the future.

**Comment by dekkerglen** [comment]
We should definitely validate these inputs - and also have more strict schemas for the cube. #974 shows a way to have strict schemas for card objects that we could use (once that is merged). We can force those fields to required so that null won't be a valid value to save.
