### ISSUE TITLE
Rainbow Fetches should count as fetches

### ISSUE THREAD

**Issue by devonrichardsz** [dekkerglen/CubeCobra#1135]
**What would you like to be able to do?**
The rainbow Fetches Prismatic Vista and Fabled Passage should count as fetches for draft. 

**Describe how you would use the feature**
It would enable the bots to draft better since these are often very important to pick. 

**Additional context**
Some cubes might want evolving wilds, command tower, and the like to fall into a similar category.

**Comment by bramleyjl** [comment]
Submitted a PR for the two rainbow fetches mentioned: https://github.com/dekkerglen/CubeCobra/pull/1166

Do we want to add additional fetchlands? Or maybe even create an alternative list for the less good ones so they get a smaller ELO boost? Off the top of my head there are:
* Evolving Wilds/Terramorphic Expanse/several other slow 5c fetches like Myriad Landscape
* Mirage fetches (these can get nonbasics) like Bad River
* Alara panoramas like Esper Panorama
* Krosan Verge
