### ISSUE TITLE
Plain text import results in CMC null

### ISSUE THREAD

**Issue by gabyreilly** [dekkerglen/CubeCobra#1136]
@APillowEdwards reported this in https://github.com/dekkerglen/CubeCobra/issues/1123#issuecomment-589553623

**To Reproduce**

(From gaby: I will ask them to include the text file used for the import.  I did notice that this is a silver-bordered set so there might be some edge cases in there :) )

**Expected behavior**

Expected all cards to be imported with CMC values

**Comment by APillowEdwards** [comment]
Hey, here's the text I imported: [message (1) (1).txt](https://github.com/dekkerglen/CubeCobra/files/4238264/message.1.1.txt)

Originally this had Sword of D&D and two instances of "Rumors Of My Death...", but I couldn't import at all with those in the list.

**Comment by ruler501** [comment]
I couldn't reproduce it getting null CMC, but I did see that it failed to import `Hazmat Suit (Used)` which does seem to be the correct name according to Scryfall.
