### ISSUE TITLE
Override Artist

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1139]
**What would you like to be able to do?**
Override the artist value on a card in my cube.

**Describe how you would use the feature**
Mark alters with the artist who did the alter or made the proxy.

**Comment by dekkerglen** [comment]
I'm nervous about this one potentially violating scryfall's terms of use by claiming a different artist is responsible for the art

**Comment by ruler501** [comment]
Could make it so you can't override artist unless you override image as
well?
