### ISSUE TITLE
Cubetutor import fails to import split cards and adventures

### ISSUE THREAD

**Issue by wirmar** [dekkerglen/CubeCobra#1140]
When importing from cubetutor, some split cards and adventures are not added to the cube.

Reason:
Cubetutor includes the "// Adventure name" in the adventure cards, cubecobra does not.
Cubetutor does not include the "// Second half name" in (some?) split cards (like "Discovery // Dispersal"), while cubecobra does include it.
Aftermath split cards are treated the same on both platforms (import works).
Fuse cards can be imported.

**To Reproduce**
Import a cube from cubetutor with adventure cards and split cards.
Example: I imported https://www.cubetutor.com/viewcube/163036 into https://cubecobra.com/cube/list/8i1

**Expected behavior**
All cards should be imported, but two cards (in my example) are missing.

**Comment by phulin** [comment]
One approach to fix this might be to check the first half of a name if the import fails, and to check to see if any card in the DB has a half-name matching.

**Comment by dekkerglen** [comment]
I think the correct thing to do is the change our card data import script. We process the split cards to add the //, and should for adventures as well

**Comment by dekkerglen** [comment]
This feature has diminishing returns as the older it gets, the more dominate our position is over CT. Therefore, I'm closing this issue
