### ISSUE TITLE
"Your profile" page breaks

### ISSUE THREAD

**Issue by nightday88** [dekkerglen/CubeCobra#1147]
From the top menu, click your user name
In the drop down, click "Your Profile"
Expected result: profile page
Result received currently: blank page (looks like empty JSON)

**Comment by phulin** [comment]
Link to show breakage: [https://cubecobra.com/user/view/5d8d4a1d884bf534916a28bd]

**Comment by ruler501** [comment]
This seems to be fixed going by that link.

**Comment by EvanFBC** [comment]
I have a broken profile page as well. The link above also seems to be broken too-- if it was once fixed, it has regressed.

https://cubecobra.com/user/view/5dbf63d811c2631e10a7bd16

Blank page with `{"level":"error"}`

**Comment by dekkerglen** [comment]
Some profile pages are now showing:
![image](https://user-images.githubusercontent.com/28238025/79655580-98592f00-8180-11ea-9e02-4808f26aec79.png)
