### ISSUE TITLE
Card preview is waaaaaaaaay too big

### ISSUE THREAD

**Issue by phulin** [dekkerglen/CubeCobra#1196]

**Comment by Vurolock** [comment]
Can you give more details? Is this on mobile, what screen resolution? Screenshots? I just increased the size to 150% because I could not read the cards easily on my 1200x1920 monitor without zooming or moving closer.

**Comment by phulin** [comment]
This is on desktop

**Comment by phulin** [comment]
I'm working on a fix now

**Comment by Vurolock** [comment]
reverting https://github.com/dekkerglen/CubeCobra/pull/1185/commits/c31561473e78b654200f1ef3ddc9055a7a695dd6 is probably the best fix, but is that the UX we are looking for?

**Comment by phulin** [comment]
I'll submit a temporary fix for the mechanical issues (flip cards have the two sides overlapped, aspect ratio is off), as well as a rewrite of the code I've had cooking for a while that makes the parameters easier to adjust.

I preferred the old size but we can go somewhere in the middle. @dekkerglen what say you

**Comment by Vurolock** [comment]
I agree fixing the flip cards is highest priority. Maybe we can look into adding setting for default card zoom size for people with poor eyesight, high-res monitors, and people that are unfamiliar with the cards.

**Comment by phulin** [comment]
See #1199 (rewrite), #1200 (destined for hotfix).
