### ISSUE TITLE
Custom Images not displayed on Draft, Sealed, Pack, or Deck pages

### ISSUE THREAD

**Issue by haganbmj** [dekkerglen/CubeCobra#1219]
**Describe the bug**
Custom images appear to only be present on the List page. Others, such as while drafting, viewing a single pack, or constructing/viewing a deck default back to the scryfall images with the Custom Image toggle not performing any visible action.

**To Reproduce**
Example cubes: 
- https://cubecobra.com/cube/samplepack/haganbmj/1584212836784
- https://cubecobra.com/cube/samplepack/mountainmage/1584212846863
- https://cubecobra.com/cube/samplepack/spekkio/1584212882942

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Nightly + Chrome + Chrome on Android

**Comment by phulin** [comment]
Thanks for reporting, I'll take a look
