### ISSUE TITLE
Download Decks

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#123]
As a user, I would like to be able to download decks in specified formats.

Let's try to get a couple formats such that we will be friendly with all the major deck building websites, and also .csv for those who prefer excel

**Comment by emmett9001** [comment]
This looks like a duplicate of https://github.com/dekkerglen/CubeCobra/issues/24

**Comment by dekkerglen** [comment]
Closed #24 
Additional deck formats requested: Riptidelab forum format
