### ISSUE TITLE
Make populate analytics a scheduled task, and save historical data for histograms

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1231]
Currently I have to manually run the script on my home computer, I would like to have it be an automated task - and instead of replacing data point, adds new ones

**Comment by ruler501** [comment]
Does the server have the RAM to run this routinely? If I remember correctly this was taking something like 6+gb just for its process.

**Comment by dekkerglen** [comment]
They do not

**Comment by dekkerglen** [comment]
This is done
