### ISSUE TITLE
Drop Down for advanced filter modal

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1235]
For the advanced filter modal, most free text fields can instead be drop down to improve user experience, such as set and artist.

**Comment by vhaso** [comment]
Sign me up! I will tackle his one

**Comment by dekkerglen** [comment]
@vhaso and updates on this? Feel free to reach out on the discord if you get stuck

**Comment by purxiz** [comment]
This is similar/duplicate to #535

**Comment by dekkerglen** [comment]
Dupe of #535
