### ISSUE TITLE
Existing draft decks do not display custom images

### ISSUE THREAD

**Issue by haganbmj** [dekkerglen/CubeCobra#1246]
**Describe the bug**
Custom card images are not displayed on viewed draft decks.

**To Reproduce**
Examples:
https://cubecobra.com/cube/deck/5e653db5cf558373d502ef75 (4 weeks old)

**Comment by dekkerglen** [comment]
This is because those attributes weren't populated at the time of creation. The only way to solve this is to create a one-shot script that goes through drafts and tries to recreate image urls, but that could get really messy and just fail as cubes have changed. 

Evidence that it's working properly:
http://localhost:8080/cube/deckbuilder/5e8e5d484a4dcb4a38555760
![image](https://user-images.githubusercontent.com/28238025/78842715-d01ce580-79ce-11ea-89aa-41525d3e9d28.png)

**Comment by haganbmj** [comment]
Right, so you're content that you're storing the same custom attributes about the cube hundreds of times?

**Comment by dekkerglen** [comment]
Yes - As the cubes change there will be cards that won't be included anymore. We'll need some way to maintain the state of the card when it was drafted, and cloning the attributes is the only way.

**Comment by haganbmj** [comment]
I'll also call out that they're not there because the field was broken/missing and not storing them. What this additionally means is that any model or ui change will break all existing decklists so you've pigeonholed yourself into more complex backwards compatibility.

**Comment by haganbmj** [comment]
Not if you isolate the references between custom images and cubelists.
Maybe it's just because I come from relational-land, but I'd rather join against custom images when I need them that way there's no concept of something being removed.

```
cube_id card_id img
```

You can expand this to encompass not just the image but all attribute overrides, which would allow you to get more accurate reporting on old decklists when a user changes the cmc/color classification of a card for example.
It's also agnostic of the current cube list meaning you don't have to worry about whether the card is actively used in the cube.

**Comment by dekkerglen** [comment]
This field is an optional override for the ground truth field that isn't stored. I don't see how this would cause anything to break down the line, or have more complex backwards compatibility. The only issue is that some card objects should have that value set when it never was, so they just won't have the custom image, and that's not a problem - they'll just behave like any other card that doesn't have that field overriden.

The issue with having a reference like that is those values are mutable, images may get changed - but if we want to preserve the deck in the state that it was drafted we must keep a copy.
