### ISSUE TITLE
Cannot open list view of my cube anymore

### ISSUE THREAD

**Issue by Pilopa** [dekkerglen/CubeCobra#1267]
**Describe the bug**
When clicking on the "List" tab in the cube overview, it just shows an error message:
"Cannot read property forEach of undefined".

**To Reproduce**
1. Go to 'https://cubecobra.com/cube/list/5d734c6486856f67522ddb25'

**Expected behavior**
The list view appears.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Smartphone (please complete the following information):**
 - Version 80

**Additional context**
My cube is a bit older. I tried to create a new cube and that worked without problems.

**Comment by dekkerglen** [comment]
Fixed on master
