### ISSUE TITLE
Filter Syntax Broken for Mana Filter

### ISSUE THREAD

**Issue by lane-eden** [dekkerglen/CubeCobra#1275]
Cube Cobra mana filter syntax does not match the Scryfall behavior.

For example, mana:{W} only returns cards that are exactly {W} whereas Scryfall returns all cards that contain {W} in their cost.

Scryfall lets you say mana={W} if you want the current Cube Cobra behavior, but mana:{W} defaults to mana>={W}. On Cube Cobra mana>={W} gives mana={W} instead.

**Comment by lane-eden** [comment]
Fixed by #1233

**Comment by ruler501** [comment]
Fixed by #1233

**Comment by lane-eden** [comment]
@ruler501 I don't think it is - mana:w still only shows white 1-drops
