### ISSUE TITLE
Cube resizing not working

### ISSUE THREAD

**Issue by Xirious** [dekkerglen/CubeCobra#1296]
**Describe the bug**
I can't resize a cube past one. 

**To Reproduce**
1. Go to any cube on my list
2. Click on "Add/Remove"
3. Click on "Resize"
4. Add any size to resize.
5. See the following error: 
`invalid json response body at http://167.172.233.110/?cube_name=xsmaybecube&root=cubecobradev.com reason: Unexpected token N in JSON at position 0`

**Expected behavior**
I expect the cube to be the size I give it. I've tried a 582 cube to 600 and it failed. I tried a single card cube to 5 cards and it fails as above. 

**Desktop (please complete the following information):**
 - Windows 10x
 - Chrome
 - Version 83.0.4103.14 (Official Build) beta (64-bit)

**Screenshot**
[Screenshot of the error.](https://imgur.com/a/T7OKSR4)

**Comment by dekkerglen** [comment]
I believe this issue is because the flask server is overloaded - I need to add more workers to it to fix it. Planning on doing some maintenance on that tomorrow.
