### ISSUE TITLE
Replace analytic page for empty cubes with message

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1303]
Per recomender:
> I've gotten some notes that "recommendations for empty cube  lists are nonsense" . . . which mathematically makes complete sense . . . the  question is if  you  care enough for us to implement something on top  of this

I think we shouldn't render the analytics page for empty cubes, instead add a disclaimer to add cards to the cube to view analytics

**Comment by GV14982** [comment]
This appears to have already been implemented, correct?
