### ISSUE TITLE
Date added field

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#131]
As a user, I would like to use the date added to Cube as a sortable card field.

When a card is added to a cube, set the date added field, and create a sort for that field as well.

**Comment by emmett9001** [comment]
I'm working on this

**Comment by emmett9001** [comment]
Does sorting by a date field have the same problem as in  https://github.com/dekkerglen/CubeCobra/pull/157#issuecomment-525698699 in which every card is in its own category?

**Comment by dekkerglen** [comment]
No, you'll see groups of cards added in the same day/update

**Comment by emmett9001** [comment]
This is done

**Comment by dekkerglen** [comment]
There is a bug with this feature: If a card's property is changed (like version) the date added field is removed.

**Comment by emmett9001** [comment]
Fixed in https://github.com/dekkerglen/CubeCobra/pull/223
