### ISSUE TITLE
Export to Tabletop Simulator

### ISSUE THREAD

**Issue by thyeggman** [dekkerglen/CubeCobra#1328]
**What would you like to be able to do?**
When exporting decks, add an option to create a Tabletop Simulator json object.

**Describe how you would use the feature**
To export decks to be used in Tabletop Simulator.

**Additional context**
This is probably a pretty expensive operation as it requires a few different things.  [Custom decks](https://kb.tabletopsimulator.com/custom-content/custom-deck/) require image grids to be generated with cards indexed into them.  A new image would need to be created for each deck.  The site frogtown.me has this functionality and hosts images on AWS:

![image](https://user-images.githubusercontent.com/13154238/80430636-064dd680-88a4-11ea-9488-27a408c701b2.png)

Here's an example of the json generated by frogtown: https://pastebin.com/G80ZWzCn

**Comment by dekkerglen** [comment]
Closing b/c this exists: https://steamcommunity.com/sharedfiles/filedetails/?id=1838051922
