### ISSUE TITLE
Recommender "No results with the given filter"

### ISSUE THREAD

**Issue by lane-eden** [dekkerglen/CubeCobra#1333]
Cube recommendations are missing and replaced with the text "No results with the given filter."

**Comment by dekkerglen** [comment]
This is due to the configuration of the ML server. We (really just I) need to setup PM2 or some equivalent to manage that server

**Comment by dekkerglen** [comment]
Fixed this issue here: https://github.com/RyanSaxe/CubeCobraRecommender/pull/15
