### ISSUE TITLE
Allow sorting or filtering by rating

### ISSUE THREAD

**Issue by thyeggman** [dekkerglen/CubeCobra#1347]
**What would you like to be able to do?**
In the "Top Cubes" search, there is a column that shows a rating.  It says it's calculated based on average pick position, and I assume it's scaled to a value from 1-100, although I can't find any place that says for sure.  Rating is not available as a filter or as a sorting option for cubes.

<img width="1133" alt="Screen Shot 2020-05-06 at 11 33 27 AM" src="https://user-images.githubusercontent.com/13154238/81215022-8dc6d400-8f8d-11ea-96d2-7e01c7eced80.png">

I would like Rating to be available as an option for filtering or sorting.  Like Elo, they should be grouped into buckets of reasonable size (possibly groups of 5?).

<img width="1138" alt="Screen Shot 2020-05-06 at 11 35 23 AM" src="https://user-images.githubusercontent.com/13154238/81215177-c9fa3480-8f8d-11ea-917c-e0e0d59e7c67.png">

**Describe how you would use the feature**
I would use it to see which cards in my cube are being drafted late, and to see how my drafters compare to the site-wide values.

**Additional context**
When using the rating to sort through top cubes, I assume the values are site-wide.  When sorting by rating within a cube, it should be clear where the values are coming from.  Two options could potentially be added: "Rating (global)" and "Rating (this cube)".

**Comment by dekkerglen** [comment]
Rating is deprecated - Elo is the replacement for rating
