### ISSUE TITLE
Be able to claim completed draft after forgetting to sign in

### ISSUE THREAD

**Issue by joshfinnie** [dekkerglen/CubeCobra#1360]
**What would you like to be able to do?**
I would like my draft saved to my account if I finish the draft but forget to sign in.

**Describe how you would use the feature**
Currently, if you draft while not signed in, the draft becomes an anonymous draft. If you sign into your account during this process, the draft should save to your account.

**Additional context**
![image](https://user-images.githubusercontent.com/125098/81693813-7759c600-942e-11ea-9171-6aaafb934dfb.png)

**Comment by dekkerglen** [comment]
I think the best way to do this, is on draft completion, show a modal that asks to login, then attempt to login with the redirect url going to the deckeditor

**Comment by dekkerglen** [comment]
I think this represents a security issue as anon users drafts could be claimed by anyone.
