### ISSUE TITLE
Card Market Integration

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1374]
**What would you like to be able to do?**
Show prices in euros from card market and have affiliate links to allow purchase of cards and tokens. 

**Describe how you would use the feature**
See more relevant prices for European users and allow extra support for the site through affiliate links. 

**Additional context**
Related to #403

**Comment by wirmar** [comment]
The card market price can be fetched via #1430 (the euro prices from scryfall are based on card market).

**Comment by Cadiac** [comment]
The scryfall data for european cardmarket cards is often a bit off though. This data doesn't contain foil cards, and it seems like that data also doesn't assume english language. Non-english (like italian or spanish) cards are often marked a little bit cheaper than they would otherwise be.

**Comment by dekkerglen** [comment]
This seems to be a tough spot then. We moved away from fetching these prices dynamically and caching them, and this integration would add back in the complexity we sought to remove. Maybe, the correct solution is to add all non-english cards into our catalog? That will have many repercussions around the site, like autocomplete. I'm very uncertain on how to move forward with this

**Comment by Cadiac** [comment]
I'll poke around this a little bit, since this feature is something that interests me.

**Comment by Cadiac** [comment]
Cardmarket does not currently offer affiliate link system. The existing affiliate program only works by asking an username of recommending account on signup, so it doesn't really work for our potential use case.

https://www.cardmarket.com/en/Magic/Help/AffiliateProgram

**Comment by Cadiac** [comment]
I had a look at the Cardmarket APIs yesterday to see what is possible and what is not. I was mainly trying to figure out ways to make buying cards missing from the cube easier.

Some limitations I met:
- Adding items to shopping list using the APIs is clunky, and we can't really make a prepopulated shopping list for the user
- The offered APIs aren't really that useful to us
- "Wants list" feature they have is is closer to something we could support. User can then search items from their wants list and automatically optimize which sellers to buy the cards from.
  - Wants list has max 150 cards size, which is too small limit for cubes
  - "Bulk import to wants list" exists, but the bulk import must be done in Cardmarkets own format
  - It is difficult to specify the version of the card. Mapping from Scryfall data to Cardmarkets expansion/version mappings is hard/impossible on special cards like the new showcase art cards.
  - Can't set foil/nonfoil on import
  - Can't set language on import
  - User can fix the card details later, but this makes us supporting these exports have little value.
- We could link to scryfall search on card name quite easily, like scryfall does.
