### ISSUE TITLE
Compare Cubes - Show Totals at Top of Screen

### ISSUE THREAD

**Issue by Gabrosin** [dekkerglen/CubeCobra#1399]
I often use the compare cubes tool to examine cubes like my own.  Having the overall count of differences between the two cubes would be a big help, rather than having to scroll through the page and do the mental math myself.

Should be as simple as re-using the header component with a title like Totals and the sums of the various other sections on the page.  Thanks!

**Comment by bramleyjl** [comment]
I'll take a look at this one.

**Comment by Gabrosin** [comment]
Thanks for the quick turnaround, the header is just what I was hoping for!
