### ISSUE TITLE
User reports cards missing when moving to/from maybeboard.

### ISSUE THREAD

**Issue by phulin** [dekkerglen/CubeCobra#1412]
```
so i tried to move the maybe board of our cube into the mainboard and i did it in small chunks
but everytime i did it some cards went missing from the maybe board (not ones i added)
and now we added like 130 cards instead of 180
```

**Comment by dekkerglen** [comment]
was this related to the nonstandard secondary sort?

**Comment by dekkerglen** [comment]
or is it a dupe of https://github.com/dekkerglen/CubeCobra/issues/1407

**Comment by phulin** [comment]
Neither, I think. I wasn't able to reproduce and I can't figure out how
this could happen in the code.

**Comment by dekkerglen** [comment]
I'll close for now until we can get a more conclusive bug report.
