### ISSUE TITLE
Support Bulk Edit

### ISSUE THREAD

**Issue by lane-eden** [dekkerglen/CubeCobra#143]
As a user, I want to be able to make bulk edits, similar to bulk upload, but supporting a format like:
Dimir Signet > Talisman of Dominance         # swap
Rakdos Signet > Talisman of Indulgence
x Bomat Courier                                              # just remove
Scrapheap Scrounger                                    # just add
...

This will require validating that removed cards are actually in your cube, and giving good error messages if they are not. Then it should draft a change list with your edits.

**Comment by dekkerglen** [comment]
Closing because this is very old, and I think this workflow has been captured already by csv import+replace
