### ISSUE TITLE
Top Cards not sorted properly

### ISSUE THREAD

**Issue by lwroots** [dekkerglen/CubeCobra#1459]
In this example where I sorted by number of cubes, Kobolds are sticked at the top of both page 1 and 2 even though they clearly do not have a high cube count.

I attached images of p1 and p2. There are no filters applied.

Sorting by elo also gives a lot of irrelevant results.

<img width="997" alt="P1" src="https://user-images.githubusercontent.com/38196962/84707047-9f53b200-af23-11ea-87f3-2afe9fc0fd65.PNG">
<img width="1039" alt="p2" src="https://user-images.githubusercontent.com/38196962/84707049-9fec4880-af23-11ea-9498-c0004d771951.PNG">

**Comment by dekkerglen** [comment]
Fixed

**Comment by lwroots** [comment]
Awesome, thanks!
