### ISSUE TITLE
Top cards results csv exportable and more than 7 pages

### ISSUE THREAD

**Issue by lwroots** [dekkerglen/CubeCobra#1460]
It's currently not possible to go more than 7 pages (280 cards) in Top Cards.
Given that cubes can be 720+ cards, it would be very valuable to go further than this - ideally you would be able to keep clicking next page indefinitely.

Also, it would be very valuable to be able to export the top cards result e.g. to csv

**Comment by dekkerglen** [comment]
Fixed - CSV export should be separate issue

**Comment by lwroots** [comment]
Awesome, thanks!
