### ISSUE TITLE
Drafting is broken at master with slightly broken draft synergies support

### ISSUE THREAD

**Issue by Cadiac** [dekkerglen/CubeCobra#1494]
**Describe the bug**
Starting a draft at current master branch fails as the code at https://github.com/dekkerglen/CubeCobra/blob/master/src/utils/Draft.js#L37 attempts to access `synergies` which is null, even though it is marked as a required PropType. This seems like a fault at current implementation which seems to be still partly in development.

**To Reproduce**
1. Checkout master 4418d213 commit
2. Go to your cube, start playtesting and begin draft
3. Draft errors at addSeen()

**Expected behavior**
Drafting works without errors at master.

**Comment by Cadiac** [comment]
This can be bypassed with additional null check at https://github.com/dekkerglen/CubeCobra/blob/master/src/utils/Draft.js#L36 for now, but hopefully the root issue with draft initialization is fixed.

`if (synergyMatrix[index][card.index] === null && synergies) {`

**Comment by ruler501** [comment]
We should assign 0 into the synergyMatrix in the case that synergies is null

**Comment by dekkerglen** [comment]
You need to add the ML server endpoint to your env variables to get the synergy embeddings

**Comment by dekkerglen** [comment]
Addressed this here: https://github.com/dekkerglen/CubeCobra/pull/1496

**Comment by dekkerglen** [comment]
We still need to fail more gracefully in the case that the ML server is down

**Comment by Cadiac** [comment]
It would make sense to fail gracefully anyways if we're building the ML server from scratch for some reason - I've been running it locally for now, but I will change my env to point to that dev server for now.
