### ISSUE TITLE
Elo displayed in Top Cards often significantly different from elo from clicking on the card

### ISSUE THREAD

**Issue by lwroots** [dekkerglen/CubeCobra#1510]
The ELO that shows up from Top Cards is often significantly different from what you see when clicking on the card.

Here's an example with Sun Titan where Top Cards say 1218 but clicking on the card says 1328, over 100 points differnece.

<img width="1281" alt="Elo from Top Cards" src="https://user-images.githubusercontent.com/38196962/86198678-c7dfcc80-bb1d-11ea-89c3-6fd7fc5a0713.PNG">

<img width="347" alt="Elo from clicking on the card" src="https://user-images.githubusercontent.com/38196962/86198680-cadabd00-bb1d-11ea-85de-5cf15a126c22.PNG">

**Comment by dekkerglen** [comment]
This is intended. It's a performance trick, some places use a cached elo that could be up to 24 hours stale
