### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#152]
As a user, I would like to setup a RSS feed for my cube, and others cubes.

**Comment by omnihound** [comment]
assign this to me

Is it ok to start using icons?

**Comment by dekkerglen** [comment]
What do you want to use icons for?

**Comment by omnihound** [comment]
for now, just as the RSS link (and generally to save some space on the screen)

I can just use text for now though

**Comment by dekkerglen** [comment]
Oh, for the user controls nav bar? Hmm. I think drop down menus might be better for that, to avoid confusion
