### ISSUE TITLE
Having ENV param flag the card base update

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1553]
I would like to have an ENV param to flag whether or not to perform the scheduled card base update. There is a small chance it fails, for reasons we don't understand right now. When that happens, the only way to fix it is to manually restart the servers. We only really need to do this update every day during spoiler season... so we can make it a env param that can be switched easily when spoiler seasons starts and ends.

**Comment by lunakv** [comment]
Given the current cadence of new product releases, I don't think this feature would really be useful anymore.
