### ISSUE TITLE
add Name as a sort/filter field

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#156]
In the Sort option on the List view, Name should be an option in the Primary Sort and Secondary Sort dropdowns. This would allow alphabetical sorting of the cube list by card name. A similar option should be added to the Filter Type dropdown in the Filter option. This would allow exact matches and regex matches on card names.

**Comment by emmett9001** [comment]
It sounds like the current coupling between filter and sort, under which both are based on the same categorizations of the cube, makes alphanumeric sorting somewhat difficult. I get the impression that whether or not we're using Scryfall syntax, the problem of needing large categories to support sorting will persist. @dekkerglen Am I missing something about how Scryfall syntax fixes the issue?

**Comment by dekkerglen** [comment]
Scryfall syntax for filtering would allow us to make a filter like "name:the" which would match true for any card with a name that contains 'the'. Check out the details here: https://scryfall.com/docs/syntax

**Comment by emmett9001** [comment]
whoops, this is a duplicate of https://github.com/dekkerglen/CubeCobra/issues/94
