### ISSUE TITLE
Peasant Cube Analytics appear broken

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1598]
Via discord:
> I'm happy to see the peasant category in the card analytics page, but every card I look at shows up in 0% of peasant cubes (even cards I've confirmed exist in listed peasant cubes, like lightning bolt).
(in the play rate tab)

**Comment by danielprue** [comment]
I found the bug fix for this, and will add a pull request soon, but I also noticed that the category detector doesn't automatically assign the peasant category as it does with pauper. Would like to also fix that in the same PR.
