### ISSUE TITLE
Bulleted lists not displaying properly

### ISSUE THREAD

**Issue by trevordahl** [dekkerglen/CubeCobra#1603]
**Describe the bug**
After adding a bulleted list to a cube description, it displays with extra spacing after the last bullet.

**To Reproduce**
1. Go to 'Cube Overview'.
2. Click on 'Edit Overview'
3. Scroll down to 'Description'
4. Using markdown, add a bulleted list.
5. Save Changes.

**Expected behavior**
I expect the spacing between all bullets to be identical.

**Screenshots**
![image](https://user-images.githubusercontent.com/7837150/93020953-2c071e00-f5ae-11ea-8873-41f5c8d0c056.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85

**Comment by dekkerglen** [comment]
Fixed in #1604
