### ISSUE TITLE
[FEATURE REQUEST] Cube sorting by cube count

### ISSUE THREAD

**Issue by lwroots** [dekkerglen/CubeCobra#1619]
There's currently tons of ways to sort the cube cards, but cube count (or cube percentage) is notably missing.

Cube count (and cube percentage) is one of the analytics when you click on card (along with elo) so I imagine it wouldn't be hard to add.
It seems very valuable to be able to sort by cube count so you can see which cards are commonly played.

**Comment by dekkerglen** [comment]
We would need to cache this data, the same way we do for Elo, and store it in the carddb files
