### ISSUE TITLE
Issues with top cards filter

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1632]
![image](https://user-images.githubusercontent.com/28238025/95794986-37d22700-0cb7-11eb-9eb5-cd12e872d3e8.png)

**Comment by dekkerglen** [comment]
Additionally: 
trying to look at cards from Innistrad and Shadows Block sorted by color, but other than W and R about half the cards don't show up
![image](https://user-images.githubusercontent.com/28238025/95795386-37865b80-0cb8-11eb-90a1-fe07a7ae96dd.png)

**Comment by JustinJDavies** [comment]
Trying to run queries very often results in HTTP 504. 

This was a query for URL https://cubecobra.com/tool/topcards?p=0&s=elo&f=coloridentity%3DG

![image](https://user-images.githubusercontent.com/10474949/95970325-b9d16580-0e07-11eb-9d26-0bd6ebde3820.png)
