### ISSUE TITLE
Cannot edit blog posts

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1633]
Trying to edit an existing blog post leads to this error:
![image](https://user-images.githubusercontent.com/28238025/95795020-5506f580-0cb7-11eb-9ed9-7f972e41e2a8.png)

**Comment by lunakv** [comment]
Looks like this was fixed by #1627 and can be closed?

**Comment by jbts** [comment]
I just tried to edit a post on the site and got a similar error.

Looks to me like the error comes from here:

https://github.com/dekkerglen/CubeCobra/blob/c102f0d12013243e6a50335b89aae15f09850803/src/components/MagicMarkdown.js#L302
