### ISSUE TITLE
Recommender suggestions background not set correctly in dark mode

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1639]
![image](https://user-images.githubusercontent.com/28238025/95795451-5a187480-0cb8-11eb-8587-4861d2a24121.png)

**Comment by dekkerglen** [comment]
Also, this: https://cdn.discordapp.com/attachments/600537623450091550/765968022824288276/Screenshot_from_2020-10-14_19-02-25.png

**Comment by ruler501** [comment]
Card names in the table of scores on the Draftbot Analysis component have a white background.

**Comment by ruler501** [comment]
Latex blocks in block quotes are illegible in dark mode, it's all light gray. Looking really closely I can somewhat make out the text as a very, very slightly different gray.

**Comment by ruler501** [comment]
Markdown quote blocks are white text on white background.

**Comment by struesdell** [comment]
> Markdown quote blocks are white text on white background.

I ran into this adding an overview to my cube with an included quote.

**Comment by jbts** [comment]
@dekkerglen I think this can be closed now with the Markdown parser replacement being merged in.
