### ISSUE TITLE
External links must specify protocol.

### ISSUE THREAD

**Issue by lunakv** [dekkerglen/CubeCobra#1645]
Add a link without a specified protocol, such as `[this](scryfall.com)` to your cube description. It will create a link to `https://cubecobra.com/cube/overview/scryfall.com` instead of the (probably intended) `http://scryfall.com`.

To actually get a link to scryfall, you must add the protocol to the address: `[scryfall](https://scryfall.com)`

This behaviour was introduced in #1624 . If intended, feel free to close this issue. Otherwise let me know and I can start working on a fix.

**Comment by dekkerglen** [comment]
I think it's not too high priority that this exists, but ideally would be fixed.

**Comment by lunakv** [comment]
After some research, it turns out that this syntax is actually supposed to produce relative URLs by the spec and this is consistent with most common Markdown parsers (Github also does this, for example). Moreover, this behaviour existed since links were introduced and I was wrong to attribute it to the PR. Given that, I'm closing this issue as something that doesn't need fixing.
