### ISSUE TITLE
Ban User + Delete all content owned by that user

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1648]
As an admin, I want the ability to have an easy UI to ban a user, and automatically delete all cubes, blogposts, drafts, comments owned by that user.

**Comment by purxiz** [comment]
Should users content be deleted immediately? I'm not saying it should stay on the site, but it would perhaps be better to hide and archive the content for a short time, both for the benefit of the user, even if they were banned it seems unfair to immediately delete what could be a lot of work, and secondly in the case of an accidental or incorrect ban?

**Comment by dekkerglen** [comment]
This is more to purge spam bots, which I've had to do a couple times manually now.

For banning actual users... It sounds like an archive system is probably the best approach. I think this is the kind of thing where we will figure it out once we need to take an action

**Comment by dekkerglen** [comment]
script created for this purpose
