### ISSUE TITLE
Add support for collaborative cube editing

### ISSUE THREAD

**Issue by GustaMagik** [dekkerglen/CubeCobra#1672]
**What would you like to be able to do?**
As a user, I would like to share the edit rights for my cube with other users on CubeCobra.

**Describe how you would use the feature**
In the cube's settings, you would be able to manage who has the rights to edit the cube. (Add, Remove)

**Comment by dekkerglen** [comment]
Duplicate of https://github.com/dekkerglen/CubeCobra/issues/1029
