### ISSUE TITLE
NODE_ENV not set correctly in production

### ISSUE THREAD

**Issue by wirmar** [dekkerglen/CubeCobra#1681]
![2020-10-29_15h36_51](https://user-images.githubusercontent.com/9307361/97588289-a2e06500-19fc-11eb-9900-6639cf0ec14b.png)

The development builds of react and jquery are used in production.
This can be fixed by starting the node server with the environment variable `NODE_ENV` set to `production`.
This environment variable will get picked up here https://github.com/dekkerglen/CubeCobra/blob/master/app.js#L219 and then used here https://github.com/dekkerglen/CubeCobra/blob/master/views/main.pug#L44.

The production builds are smaller and do not include unnecessary checks that slow down performance.

**Comment by dekkerglen** [comment]
Doing this in production currently causes the server to fail to start. Needs more investigation

**Comment by wirmar** [comment]
I just tried to fix the issues why it doesn't start in production. But now the server side rendering seems to introduce a lot of subtle bugs in the code 🤔
I will look into it a bit more, but maybe disabling server side render is the saver option? (Which would still allow using the production builds of the dependencies.)
