### ISSUE TITLE
Redirect to HTTPS

### ISSUE THREAD

**Issue by lunakv** [dekkerglen/CubeCobra#1687]
As a user, I would like all CubeCobra content to be served through HTTPS. The HTTP server should then serve only to redirects all requests to the encrypted protocol.

This could be done either through node in `app.js` or in the reverse proxy settings. I don't know what the AWS setup looks like, so I can't comment on which approach would be better.

**Comment by dekkerglen** [comment]
This is something I can configure in the AWS load balancer

**Comment by crookedneighbor** [comment]
Just came here to report the same thing and was happy to see an issue had already been opened.
