### ISSUE TITLE
Shareable filters

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#169]
As a user maintaining a cube that contains an interesting subset of cards, I'd like to be able to share a filtered view of my cube. Ideally I'd do this by setting up the filter and then copy/pasting the URL from the nav bar. This would allow me to share a view of my cube minus the power expansion, for example.

https://github.com/dekkerglen/CubeCobra/issues/3 has implications for how this would be implemented.

**Comment by emmett9001** [comment]
In progress in https://github.com/emmett9001/CubeCobra/pull/3

**Comment by emmett9001** [comment]
Pull requested an implementation https://github.com/dekkerglen/CubeCobra/pull/235

**Comment by emmett9001** [comment]
Done

**Comment by dekkerglen** [comment]
Could this be extended to a sort as well? If no sort is shared, it goes by the default sort.

**Comment by emmett9001** [comment]
Yup, tracked in https://github.com/dekkerglen/CubeCobra/issues/237
