### ISSUE TITLE
Bot Didn't Pick the Card With the Highest Score

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1695]
https://cubecobra.com/cube/deck/5f9eef1733dbe856b95747c2?seat=1&view=draftbot&pick=3
https://cubecobra.com/cube/deck/5f9eef1733dbe856b95747c2?seat=1&view=draftbot&pick=19

The bot picked the 4th highest card according to the analysis in both these picks.

https://cubecobra.com/cube/deck/5f9eef1733dbe856b95747c2?seat=1&view=draftbot&pick=15

In this one it picked the second highest score.

**Comment by dekkerglen** [comment]
This isn't an issue with the draftbots, but rather replicating the draft bot breakdown
