### ISSUE TITLE
Cube Diff

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#17]
As a user, I would like to be able to diff/compare two cubes, to see what cards they have in common, and what cards are unique to each cube.

Have a button on a cube labeled 'Compare to...' and have the option to select one of your cubes to compare that cube to. Alternatively, come up with an elegant way to select two unowned cubes to diff. The diff should have three columns with only a secondary sort active.

**Comment by lane-eden** [comment]
I'll take this one

**Comment by lane-eden** [comment]
Added in #186
