### ISSUE TITLE
Draft cannot be completed for specific cube

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1700]
Cube: https://cubecobra.com/cube/overview/5f9710ee56de12418c7d0431
OS: Windows 10 64-bit and Android 11 on Pixel 5
Trigger: Finish a standard draft, Finish a bots-only standard draft
Expected: Draft should complete and view should progress to deck editing or deck viewing
Actual: View reverts to top level Playtest page, with the message
Deck validation failed: seats.0.pickorder.0.finish: `` is not a valid enum value for path `finish`., seats.0.pickorder.0.status: ` is not a valid enum value for path `status`., ... (continues for seats 0..7, pickorder 0..44. Added escapes for formatting)

**Comment by dekkerglen** [comment]
Looks like several updates were done via CSV, so the issue is that CSV upload is not setting some fields correctly.

**Comment by struesdell** [comment]
After updating my CSV to omit the offending fields, I'm able to draft as expected.
