### ISSUE TITLE
A More Generic Custom Draft Pack Specification System

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1716]
**What would you like to be able to do?**
Our current system for specifying custom packs is quite powerful, but has many limitations. Most notably you cannot have meaningful dependencies between slots(there is the dependencies created by the without replacement methodology, but those are almost impossible to utilize). There is also the issue of as we add more things you can specify on each pack the current ui is going to get cluttered and harder to use. Creating an advanced UI with the full capabilities could solve this. Personally I'd prefer some kind of DSL for specifying packs. It would allow you to specify all the packs in one file and enable attaching attributes to each pack separately. It would be created so that for each player the corresponding pack would have the same number of cards and the same attributes. For adding cards it would allow you to filter through the cube using our filter system to create lists that you could extract a random element from with or without replacement(in the case of without replacement this would propagate back to the cube  through all intermediary lists, would have to decide if it should propagate to all other defined lists as well).

**Describe how you would use the feature**
Here is a specification for packs I created in a DSL from an old project. We could make significant improvements on the syntax.
Basically this specification adds rares, lands, and uncommons just by randomly selecting off filtering like we can currently do. Then for commons it ensures that 3 are one color, 3 are another color that is the other color's ally, one card that is both of those colors, a colorless card, and 2 cards without any further restrictions. In our current system it is impossible to specify the requirement that 3 cards are the same color which is chosen at random for each pack.
A more in-depth explanation is that this specification creates 1, 15 card pack with no attributes. It has one card taken without replacement that is tagged as a `Lands` where there's one copy of each card, similarly one `Rares` with one copy. It specifies there are 2 copies of each of the cards marked `Uncommons`. It gets one card marked as `Uncommon` and `Allies`, it gets one card marked `Uncommons` and `Mono`, and one more card that just needs an `Uncommons` tag. For the commons it specifies 4 copies of each are available. Then it does does something that our current system can't do. It first creates a list of all Ally colored pairs, then it filters those to just the pairs where for both colors there are at least 3 cards tagged with `Commons` and that color. It chooses one of those pairs at random and adds 3 cards that are tagged `Common` and that specific color, it adds one card whose colors contains or equals the pair that has the `Commons` and `Allies` tag, it adds one card which has the `Commons` and `Colorless` tag, finally it adds two cards that just need to be tagged `Commons`.

```
Lands
    Any -> Card
    Add(Card)

Rares: 1
    Any -> Card
    Add(Card)

Uncommons: 2
    GetList('Allies') -> Card
    Add(Card)
    GetList('Mono') -> Card
    Add(Card)
    Any -> Card
    Add(Card)

Commons: 4
    Colors = ['White', 'Blue', 'Black', 'Red', 'Green']
    Allies = Zip(Colors, Rotate(Colors,1))
    [Allies as (X0, X1) where ContainsAtLeast(GetList(X0), 3) and ContainsAtLeast(GetList(X1), 3)] -> FinalColors
    FinalColors /> FColor, SColor
    FColorList = GetList(FColor)
    SColorList = GetList(SColor)
    Repeat 3 {
        FColorList -> Card
        Add(Card)
    }
    Repeat 3 {
        SColorList -> Card
        Add(Card)
    }
    Allies = [FColor, SColor]
    [GetList('Allies') as X where Subset(GetColors(X), Allies)] -> Card
    Add(Card)
    GetList('Colorless') -> Card
    Add(Card)
    Repeat 2 {
        Any -> Card
        Add(Card)
    }
```

**Additional context**
Consideration needs to be given when creating the language to how difficult it will be to calculate asfans for the resultant packs.

I could also see this as a JSON object of some kind potentially, though I'm not entirely sure how things like variables carried between card definitions would work there.

I am leaning towards having no propagation of removal without replacement. It makes some things more verbose, but gives a lot of useful power and makes interactions much easier to understand. 

As far as asfan goes any decently generic system will be extremely complicated to implement and likely very slow. I'd propose that we just do simulation instead. For the case of removal without replacement, if we generate 300,000 independent drafts then for any copy of a card that appears at least once every 660 player pools(cards 1 player opens for a draft) for an 8 player draft(170 for 2 player and 340 for 4 player) we can be about 99.5% sure that we are at most 5% off of the correct answer. If we want to do generation the same way we do now, that is assuming each players pool is independent(which is only roughly the case do to removal without replacement) we would need to generate 700,000 independent pools which is for all except the 2 player instance significantly less than generating complete drafts. For removal with replacement it is a little more complicated since you have to consider the standard deviation of the card's asfan. For the case of generating full drafts using 300,000 as above we'd have the same 99.5% surety of being within 5% of the correct asfan if the standard deviation of the asdraft(number of times it appears in any pool of 1 draft) is at most 70 times the asfan(for a pool) for 8 players(35 for 4 players, 18 for 2 players). Though it is important to note that since it is without replacement every pool should be independent. For just generating the pool using 700,000 samples as above you get that the stddev of the asfan(for a pool) must be at most 14 times the actual asfan of the pool for the desired accuracy. We'd have to run some performance tests to see how feasible hundreds of thousands of trials are, but it should provide very good results.

**Comment by ruler501** [comment]
Adding this as a comment so it can be addressed independently of the main issue. Here is roughly the description of the language I would propose.
Dynamically typed so we don't have to implement a type checker, but variables still have types. 3 basic types which are String, Number, Card, and Array that holds a heterogeneous sequence of values. There are no references, everything is a separate value. There is one implicitly defined variable `Cube` which is an Array of Card objects containing the cards of the cube.
A program would be a new line separated sequence of statements. There are 2 kinds of block statements that contain other statements, statements do not have to be in a block.
1. A Setup Block is statically run once before any other code, it must be the first statement in the specification and there can be at most one, it is not required. All variables defined in this block as well as the `Cube` variable are shared between all players and updates made in the specification for one player will be carried over to the next player. They would be used to setup any variables that need to be shared between all players. An example would be adding extra copies of Commons so you only need 1 in your cube, but can generate as though there were 4. It would look like:
```
Setup {
... 
}
```
2. A Repeat Block is just syntactic sugar for repeating a sequence of statements a fixed number of times. The parameter to the block must be an integer constant. It would look like:
```
Repeat 4 {
... 
}
```
There are 5 other kinds of statements:
1. Variable assignment `<VariableName> = <ValueExpression>` which works as you would expect
2. Random Extraction(Random Sampling Without Replacement) `<VariableName> -> <VariableName>` where the first variable name must be a non-empty Array or an error stops execution. It pops a random element of the array and assigns it to the given variable name.
3. Random Sampling(With Replacement) `<ArrayValueExpression> ~> <VariableName>`. Basically the same as Extraction, but it doesn't change the array and so can also sample from temporary arrays.
4. Add Card statement `AddCard(<CardValueExpression>)` adds the specified Card value to the current pack(see next statement). If the expression does not evaluate to a Card value execution halts with an error. This cannot appear in a Setup Block. 
5. Start Pack statement `StartPack{property1 = <ConstantValue>, property2 = <ConstantValue>, ...}`, or if no properties are specified `StartPack{}`. There would be a defined set of properties with specific types that would change how that pack is drafted. Examples would be whether it is sealed, how many cards to pick at a time, etc. This let's the generator know to start a new pack. There must be a Start Pack statement before any Add Card statements and Start Pack statements cannot appear in Setup blocks.

ValueExpressions are all pure(don't modify arguments or global state, and don't read global state other than looking up the values of specified variables) built as follows:
1. Numeric Constants `\d+(\.\d+)?`, String Constants(double or single quoted using the same semantics as the filters), Array Constants `[<ValueExpression>, ...]`.
2. `<VariableName>` evaluates to the current value of the variable. Error if the variable is undefined.
3. `+, -, *, /, ^` as binary operators on numbers without any precedence. Errors when appropriate.
4. `<ArrayValueExpression> @ <IntegerValueExpression>` the value at the specified index of the array(1 indexed). 
5. `Concat(<ArrayValueExpression>, <ArrayValueExpression>, ...)` concatenate multiple arrays into one array value, type checking if needed. The arguments are alternatively allowed to be all either String values or Number values. In that case it converts them all to strings and concatenates the string.
6. `Zip(<ArrayValueExpression>, <ArrayValueExpression>, ...)` creates an array of arrays with the first dimension equal to the length of the shortest input array and inner dimension equal to the number of arrays provided. Each element at index i is the array made up of the elements at index i from each of the provided arrays.
7. `Rotate(<ArrayValueExpression>, <IntegerValueExpression>)` does a circular right rotation of the array by the given number of positions.
8. `IndexOf(<ValueExpression>, <ArrayExpression>)` the index of the array(1-indexed) where a value compares equal(deep equality) to the value. Error if no such element exists.
9. `GetPropertyOf(<CardValueExpression>, <StringValueExpression>)` get the property of the card specified by the string. If the string does not specify a property error.
10. `LengthOf(<ArrayOrStringValueExpression>)` the length of the array or string. If the value is neither error.
11. `UniqueElementsOf(<ArrayValue>)` a new array where no two elements compare equal(deep equality) containing the maximal number of elements from the given array.
12. `RemoveValueAt(<IntegerValueExpression>, <ArrayValueExpression>)` a new array equal to the given one with the value at the specified index(1 indexed) removed. If the index is not a valid index of the array error.
13. `[<ValueExpression> for <VariableName> in <ArrayValueExpression> where <BooleanExpression>]` which is where most computation will take place filters and transforms arrays. The expressions can access the current element of the given array using the given variable name. After the expression is done evaluating the given variable will have a value of the last value in the given array, or not be changed(including defined) if the given array is empty. You don't have to include `<ValueExpression> for ` in which case it will be an identity transformation not modifying the values from the array when creating the new array. You similarly don't have to include ` where <BooleanExpression>` in which case it won't filter out any elements of the array. So technically `[<VariableName> in <ArrayValueExpression>]` is valid and would just evaluate to the given array.

Finally there are boolean expressions which can only occur within comprehensions.
1. `<BooleanExpression> <and|or> <BooleanExpression>` evaluates as expected.
2. `Not(<BooleanExpression>)` evaluates to true iff its argument evaluates to false.
3. `<, <=, >=, >` are binary operators on two strings in which case they behave lexicographically, or two numbers in which case they follow the standard ordering.
4. `<ValueExpression> == <ValueExpression>` deep equality comparison between 2 values. Evaluates to false if they are different types.
5. `ElementOf(<ValueExpression>, <ArrayValueExpression>)` evaluates to true iff there is an element of the array that compares equal(deep equality) to the value. 
6. `Contains(<ArrayValueExpression>, <ArrayValueExpression>)` evaluates to true iff every element of the second argument compares equal(deep equality) to different elements of the first argument(Multiset equality).
7. `Intersects(<ArrayValueExpression>, <ArrayValueExpression>)` evaluates to `LengthOf([X in A1 where ElementOf(X, A2)]) > 0`.
8. `Subset(<ArrayValueExpression>, <ArrayValueExpression>)` evaluates to `LengthOf([X in A2 where ElementOf(X, A1)]) == LengthOf(A2)`
9. `SetEquals(<ArrayValueExpression>, <ArrayValueExpression>)` evaluates to `Subset(A1, A2) and Subset(A2, A1)`
10. `FilterMatches(<StringValueExpression>, <CardValueExpression>)` evaluates to true iff the filter specified by the string is true for the card. Note that as of now the other boolean expression constructions are sufficient to do nearly everything the filters can do(exceptions for the mana cost being payable with queries) and more, but I think this would be appreciated to make it simpler to write and test.

I'll edit in examples of common requests later.

**Comment by RKelln** [comment]
I like the idea of DSL, supported by a bunch of built-in common pack filling scenarios that can be chosen by users and then easily (with nice UI) have their variables adjusted to fit the cube. Those would spit out DSL. 

Some quick first bikeshedding/sugar thoughts about DSL:
Having a `Pack` object that receives cards might be nice as a replacement for `AddCard(card)`:
```
card -> Pack
```
Not sure if it would be possible/useful but Pack(i) could put into a special pack by number and Pack(name) could put into a pack by name (and create pack if it didn't exist).
 
Other sugar could be adding a number to the `->` operator to choose that many, but not sure how that looks best? Thus:
```
Repeat 3 {
    commons -> common
    AddCard(common)
}
```
with the most "english sounding" syntax becomes:
```
3 commons -> Pack
```
But that seems like it might be a parsing nightmare, maybe `3 * commons -> Pack` ?

I don't like how similar `~>` and `->` are, maybe `+>` and `->` where `+>` is random sample/choose. `=>` could copy all?
Having a non-repeating sampler (choose from least chosen) that doesn't remove might be useful as well. Say `#>`.

Sugar for `Cube = RemoveValueAt(IndexOf(card, Cube), Cube)` such as `Cube -= card` might be nice too.

Sugar for select/filter on Cube/Pack/array?  
```
Cube[card] -> card_removed_from_cube
3 Cube["rarity:common"] -> up_to_3_commons_removed
Cube[i] +> copy_of_card_at_index_i
```

So generic cube looks like:
```
Setup {
  3 * Cube["rarity:Common"] => commons
  2 * Cube["rarity:Uncommon"] => uncommons
  Cube["rarity:Rare"] => rares
}
Repeat 3 {
  StartPack{}
  10 * commons -> Pack
  3 * uncommons -> Pack
  rares -> Pack
}
```
Or even this (not quite the same, but very simple and resistant to weird numbers of cards in cube):
```
Repeat 3 {
  StartPack{}
  10 * Cube["rarity:Common"] #> Pack
  3 * Cube["rarity:Uncommon"] #> Pack
  Cube["rarity:Rare"] #> Pack
}
```

**Comment by ruler501** [comment]
I like the idea of having a `Pack` special variable that is not assignable to, but I have some concerns over the syntax. Currently extraction assigns the extracted value to the variable name on the right. The proposed syntax would suggest that if the right hand side is a variable with an array value it appends instead. That isn't what we'd always want though and isn't always intuitive. I'd propose `->>` for appending extraction.

I don't really want to handle pack references so I think we'll skip that for now.

For extraction with count I think `<IntegerConstant>x <VariableName> -> <VariableName>` for assigning a randomly chosen array of the given size to that variable name would be reasonable. It would be possible to parse without the x as well.

I don't want to overload the extract syntax for inserting a specific value into an array. Maybe overload +/-/* to work with arrays such as `<IntegerValueExpression> * <ArrayValueExpression>` for concatenating to itself and `<ArrayValueExpression> + <ValueExpression>` for creating a new array with the value appended, `-` would be similar removing the first instance from the array. This doesn't work for the desire to use it to add a card to a pack though. Any ideas for that are welcome.

I like `+>` instead of `~>`. I don't really think there's a need for `=>` since we already have concat. `#>` seems like it would be confusing to use. 

Compound assignments may be worth considering(and would solve the issue of using `+` with `Pack`), but it does add more syntax without much extra functionality which could make it harder to learn.

It may be good to add `AddCards` to accept arrays of cards to allow adding several cards at once look like
```
9x commons -> cards
AddCards(cards)
```
The issue here is that it removes the guarantee we currently have that every corresponding pack for each player will have the same number of cards.

So far I've carefully avoided using standard array subscript notation because I thought people might find it confusing since it looks the same as defining an array. I'd really prefer some new syntax that would read roughly as Array where filter.

**Comment by ruler501** [comment]
https://gist.github.com/lunakv/ddcf24d6d3c31de3f874b2b28b83c6ff
Is an outline of what a JSON schema for pack specifications might look like. From @lunakv

**Comment by ruler501** [comment]
Here are the current considered changes to the DSL. Ones that have been applied to the [specification](https://github.com/dekkerglen/CubeCobra/issues/1716#issuecomment-728673751) are marked.

- [ ] Change the sampling(with replacement) operator from `->` to `+>`.
- [ ] Add an if expression. For syntax I'm not entirely sure what is the easiest for non-programmers to learn. Currently considering pythonic `<Expression> if <BooleanExpression> else <Expression>` or more like the functional languages `if <BooleanExpression> then <Expression> else <Expression>` it may be better to use different keywords such as `otherwise` that read more like English. It should be an expression not a statement because we want to have a single control flow path.
- [ ] Add syntax for extracting multiple values at once from an array. The proposed syntax is `<IntegerConstant>x <ExtractionStatement>` which would assign an array of the given count of random choices from the array. Roughly equivalent to `result = [] \n Repeat N { \n array -> x \n result = Concat(result, [x]) \n }`
- [ ] Extraction operators for appending to an array variable instead of assigning to the variable. I don't know how intuitive it is but inspired by shell redirection it could be `->>`.
- [ ] `<IntegerValueExpression> * <ArrayValueExpression>` for concatenating an array to itself a given number of times.
- [ ] `<ArrayValueExpression> + <ValueExpression>` to concatenate a value to an array. Short for `Concat(array, [value])` notably it does not modify the arguments.
- [ ] `<ArrayValueExpression> - <ValueExpression>` to remove the first instance of the value from the array. Short for `RemoveValueAt(IndexOf(value, array), array)`.
- [ ] a syntax for extracting directly into the pack instead of requiring multiple statements. Using a special variable that cannot be assigned to that always represents the current pack such as `Pack`. This would require the appending extract operator from above. 
- [ ] Short syntax for using a filter on an array of cards. A proposed syntax is `<ArrayValueExpression>[<StringValueExpression>]` which would be short for `[card in array where FilterMatches(filter, card)]`.
- [ ] An expression for sampling(with replacement). Something like `RandomValueFrom(<ArrayValueExpression>)`. Shouldn't have one for extraction without replacement because by design all expressions are pure. Random choice in this case is not actually pure because it mutates a global variable(the deterministic random number generator that was initialized with some seed). This is probably an acceptable thing  though.
- [ ] a form of lambdas for the unique elements function, possibly for the set comparison functions as well. Rough syntax could be `UniqueElementsOfBy(<ArrayValueExpression>, <Lambda>)` where the lambda syntax is to be determined. Potentially something like `<VariableName> to <ValueExpression>`. This would be especially useful to allow making things like an array of cards with unique names which can sort of be accomplished by `[[c in array where GetPropertyOf(c, "name") == name]@1 for name in UniqueElementsOf([GetPropertyOf(c, "name) for c in array])]` which can be adapted for any transformation. 
- [ ] a sort function for arrays of comparable types(strings and numbers). This would be especially good if the lambda syntax was adopted to allow sorting Cards
