### ISSUE TITLE
run mongodb on a separate cluster

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#173]
Currently the mongodb database backing the app runs on the web server's `localhost`. This blocks https://github.com/dekkerglen/CubeCobra/issues/172. The mongodb database should run on a separate cluster in production. This can likely be enabled by using the managed MongoDB [offering](https://marketplace.digitalocean.com/apps/mongodb) from Digital Ocean.

Steps
* [ ] parameterize database connection strings
* [ ] swap between localhost and external cluster for local development and prod deployment
* [ ] provision mongodb cluster

**Comment by emmett9001** [comment]
@dekkerglen is working on this

**Comment by dekkerglen** [comment]
I'm assigning myself but not actively working on this, when we reach a stable build for the next release, and fix any bugs that appear after that, I'll setup the dev server with this setup and we can ship it with the following release
