### ISSUE TITLE
Carry over url params on cube edit

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1738]
When I go to Visual Spoiler View, then make changes from there and commit them, the page reloads in list view. Also, when I return to spoiler view, if I had before switched to Large card size, it will have reset to Medium.

Solution: Append the url query params to the submit endpoint - that way after reloading the page, it will go back to the view it was at.

**Comment by brandonwharton** [comment]
I'm working on this one.
