### ISSUE TITLE
Adjust scrollbar for dark mode

### ISSUE THREAD

**Issue by lunakv** [dekkerglen/CubeCobra#1770]
In dark mode, the site uses the default horizontal scrollbar, which is usually white. That can be visually jarring. We should adjust the scrollbar color in dark mode so it matches the rest of the theme.

**Comment by nicolinilr** [comment]
Hi I'd like to work on this issue, but I ran into a (possibly simple) roadblock: in my local cubecobra, I can't login (as it's not connected to the account database), but as a result I can't access my account change to get to darkmode and see my changes. Is there a development user/pass for the local copy?

**Comment by ruler501** [comment]
You can register like normal through the web interface.
