### ISSUE TITLE
Card pages should handle DFCs better

### ISSUE THREAD

**Issue by lunakv** [dekkerglen/CubeCobra#1796]
Our current card page has problems displaying double-faced cards (picture below as an example). The page for a DFC's front face shows the name, cost, and type line of the front face only, then combines the oracle text of both faces, after which it displays the P/T or loyalty of the front face.

Aside from the aforementioned oracle text, the back face isn't indicated anywhere on the page except somewhat confusingly in the Versions list (and that's only for TDFCs) and in Autocard links.

As a user, I'd like to have a clearer separation between the front and back faces of a DFC and a clear link from one side of a DFC to the other. The issue of adequate separation also applies to split cards, which show both mana costs and names, but concatenate the oracle texts and show only the type line of the first part.

![Screenshot from 2021-01-17 11-18-36](https://user-images.githubusercontent.com/38463785/104837710-4c255180-58ae-11eb-9949-3df460bf28c8.png)

**Comment by ruler501** [comment]
The best way to handle this would probably be to have a property of the card with an array of cardID's for the other face/split(s)
Then we can add some UI to render the other part(s). This would be the least intrusive into the card object since we really don't track properties of other faces very well currently.

**Comment by lunakv** [comment]
I don't think this issue should be closed. #1840 solves part of the problem, but there are still several unresolved issues mentioned here.
