### ISSUE TITLE
Maybeboard Improvements

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1815]
**What would you like to be able to do?**
 - Be able to fully customize cards in Maybeboard with overrides and tags. 
 - Be able to add a card from Maybeboard directly to the cube with overrides and tags intact. 
 - Move cards from Cube to Maybeboard directly.
 - Have whether the maybeboard be a query param so I can send links showing it or have a bookmark with it open. 

**Describe how you would use the feature**
Provide more utility to the Maybeboard as a holding ground for considered cards.

**Comment by alexzhaohong** [comment]
Am I allowed to include my own opinions here? I too want to "Provide more utility to the Maybeboard as a holding ground for considered cards."

**What would you like to be able to do?**
Add cards to my Work-in-progress Cube quickly

**Describe how you would use the feature**
1. Have a Bookmark to https://cubecobra.com/cube/list/asymmarian-board-complexity

Currently I do this process when I randomly think of a card:
0. Click on my Bookmark
1. Click "Add/Remove"
2. Type the card I want to add
3. Click "Add"
4. Click "Save Changes"

Improved Process
0. Click on my Bookmark URL that default shows Maybeboard
1. Type the card I want to add
2. Click "Add"

**Comment by ruler501** [comment]
@alexzhaohong I added that to the list.

**Comment by lunakv** [comment]
Moving cards between the maybeboard and the main list should probably still happen through the Add/Remove modal, otherwise we're breaking continuity of the blog updates.
