### ISSUE TITLE
Allow cards in Packages to have overrides pre-applied

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1886]
**What would you like to be able to do?**
Add overrides to my packages, such as tags, custom images, custom type, color identity, and so on. 

**Describe how you would use the feature**
Better handle packages where the default properties could use some tweaks to be more convenient (think color identity on fetch lands).
Have packages of alters with the images showing what they would look like. It could be really cool if artists could make packages like this for packages they sell of cards they alter. 
Take a step towards better managing custom cards. 

**Additional context**
Owned probably shouldn't come from the package value.
Might be good to have a toggle for if you want to add the card with no ovverides.

**Comment by dekkerglen** [comment]
I think this is out of scope for the package feature, closing
