### ISSUE TITLE
Renaming tags

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [dekkerglen/CubeCobra#1902]
**What would you like to be able to do?**
Be able to change the name of a tag across all cards (as opposed to deleting the tag from each card individually and then adding a new tag)

**Describe how you would use the feature**
It would allow me to add a prefix to each tag so that when I sort by tag (which is sorted alphabetically) they appear in the sort order I desire.

I love this software, thanks for all you do!

**Comment by lunakv** [comment]
This is achievable through the group edit modal.
1. Set primary sort to `Tags`, the rest to `Unsorted`
2. Find the tag you want to rename and click the group header
3. In the modal that appears, under `Edit Tags`, fill in the new tag and save.
4. Repeat the process, except you select `Delete tags from all` and fill in the old tag.

**Comment by LiterallyUniqueLogin** [comment]
Thank you! That works perfectly.
