### ISSUE TITLE
"Specify versions" when adding cards is broken when a set has multiple versions of the same card

### ISSUE THREAD

**Issue by nex3** [dekkerglen/CubeCobra#1910]
**Describe the bug**

When adding a card to a cube, if one set has multiple versions of the same card, CubeCobra will choose only one of those versions and only make that one available to add. All versions show up in the autocomplete, but the associated hover images only show the given version and regardless of which version the user selects only the given version will be added.

**To Reproduce**

1. Go to a cube's List page.
2. Click on "Add/Remove".
3. Select "Specify Versions".
4. Type in the name of a card that has multiple versions *in the same set*. Any rare from a set Eldraine forward will work. Let's use Charming Prince as an example.
5. Hover both "Charming Prince [eld-8]" and "Charming Prince [eld-335]". Note that they both display the image for "Charming Prince [eld-8]".
6. Select "Charming Prince [eld-335]".
7. Select "Save Changes".
8. Scroll down to Charming Prince in the cube list and note that the version that was added is "Charming Prince [eld-8]".

**Expected behavior**

In step 5, the image for "Charming Prince [eld-335]" should display when hovering. In step 8, "Charming Prince [eld-335]" should be the one in the cube.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 90.0.4430.93

**Comment by dekkerglen** [comment]
Fixed in prod
