### ISSUE TITLE
Migrate to Node 14

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1933]
We should move to Node 14 to take advantage of newer features and move towards a unified codebase instead of needing webpack to go between node and browser code.

*Update: Migrate to node 16 instead

**Comment by lunakv** [comment]
I looked through the changelog of Node 14 and none of the changes labeled as `semver-major` should impact us. I've also been using 14 on my local dev instance for several weeks and didn't encounter any problems with it. I believe this is safe to deploy on the dev server right now.

**Comment by samjbow** [comment]
This issue has been around for about a year now and the current Node LTS version is now 16.15.0 - maybe this should be the new target instead?
