### ISSUE TITLE
Expletive Filter

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#195]
As an admin, I don't want my site to display user entered expletives.

User some npm library like: https://www.npmjs.com/package/noswearing

Make this applicable to all user entered fields: Username, Cube Name, Cube Description, Blog Posts, Cube URLS

**Comment by lane-eden** [comment]
I like the looks of this one: https://www.npmjs.com/package/bad-words - I'll try it out.

**Comment by dekkerglen** [comment]
Should I assign this to you?

**Comment by lane-eden** [comment]
Yeah sure

**Comment by lane-eden** [comment]
Added in #238
