### ISSUE TITLE
"Remove" preview card image does not match included version

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#196]
When hovering card names in the autocomplete list for the Remove text field in the Add/Remove view, the card preview image does not always match the version of the card included in the cube.

1. Navigate to List, then Add/Remove
2. Type any card name in the Card to Add field
3. Start typing the name of a card in the cube with at least two different artwork releases in the Card to Remove field
4. Mouseover the name of the desired card in the autocomplete list
5. Observe that the card preview image is the most recent printing as opposed to the image configured for the cube

In this situation I'd expect the preview image to match the image I've selected for the given card in my cube.

- OS: Ubuntu 16.04
- Browser: Chrome 70.0.3538.77

**Comment by dekkerglen** [comment]
This would actually require a rewrite of the remove autocomplete, as it used only card names, and then fetches the image. Not an easy issue
