### ISSUE TITLE
Going to a wrong cube id infinitely redirects

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1966]
Like: localhost:8080/c/cube_id_that_doesnt_exist

**Comment by lunakv** [comment]
If you look at where the redirect cycle is happening, is it at `/cube/list/404`? If so, that's not actually a bug, just the way we handle redirects. For cube links on cubes that aren't found, we redirect to a cube with ID 404. If that cube doesn't exist in your local DB, then this will loop, but in prod it just returns a "Cube Not Found" cube.

**Comment by ruler501** [comment]
@lunakv is correct here, the fix is to create a cube with shortID 404.

**Comment by dekkerglen** [comment]
Dev server falsely had this issue
