### ISSUE TITLE
Custom draft format not transitioning to deckbuilding

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1984]
https://cubecobra.com/cube/playtest/wtwlf123

Glimpse Draft

**Comment by dekkerglen** [comment]
Issue still occurring

**Comment by ruler501** [comment]
hmmm. It must be intermittent then since this did fix the reproduction of the issue I tested with.

**Comment by roborocket** [comment]
After final two picks/random trash remaining in custom supreme draft format, the request was spinning for about a minute before loading deckbuilding page. Also it made a bunch of decks with each pick:
![Recent Decks](https://user-images.githubusercontent.com/59295312/120879086-30c99300-c57e-11eb-941f-5b305bd5e311.png)

**Comment by roborocket** [comment]
After some testing got the draft to only build one deck. Changed the format to 2 seats with 18 15-card packs, each with the same three steps: 1) Pick 2; 2) Randomly trash 13; 3) Pass. That got me to deck building after about a two minute wait. Console was showing gateway timeout errors until the page finally loaded. Putting the pass step at the end of each pack, or maybe more importantly after the random trash step at every instance, seems to have stopped the deck builder from making a billion decks. The process is still very slow, though. Is the culprit the number of seats? Supreme draft should just be a one-seat option anyway, which isn't currently supported.

**Comment by roborocket** [comment]
Gotta say though, the random trash visual on thirteen cards is extremely satisfying.

**Comment by ruler501** [comment]
There's a visual? I would've thought it would be too fast to see.

**Comment by ruler501** [comment]
So what's likely happening is it's submitting the form over and over again until it gets a redirect response back which isn't great.

**Comment by dekkerglen** [comment]
I believe this is the full error:
```
{
    "level": "error",
    "message": "Cannot read property 'toLowerCase' of undefined",
    "target": "/cube/deck/submitdeck/5d61aa23b8ec593ca4b76ca6",
    "uuid": "838b75d5-7076-4a5e-8d54-0edb3ab7ebcc",
    "stack": [
        "TypeError: Cannot read property 'toLowerCase' of undefined",
        "    at /var/app/current/serverjs/cubefn.js:369:37",
        "    at CoreDocumentArray.findIndex (<anonymous>)",
        "    at addDeckCardAnalytics (/var/app/current/serverjs/cubefn.js:368:42)",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "    at async /var/app/current/routes/cube/deck.js:675:5"
    ]
}
```

**Comment by lunakv** [comment]
This error is only part of the problem. It already existed in the last release and there are reports of it appearing even without this submission issue. While investigating this a while back, the hypothesis I came up with is that the `CubeAnalytic` db objects for some cubes were corrupted so that they contain entries without a defined `cardName` property. That then results in this error being thrown.

I can't verify this hypothesis due to not having db access, but @dekkerglen if you could check the Analytic object for the cube this was submitted for (and specifically the `cards` array of that object), you should be able to pretty easily confirm/deny it.
