### ISSUE TITLE
Draftbot and pick by pick breakdown aren't working

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1994]
https://cubecobra.com/cube/deck/60ba7c51f22cf71061b28b5b?seat=6&view=draftbot&pick=30

The pack data for individual picks seems to not be getting populated correctly. The issue is likely in the `getDrafterState` function.

**Comment by dekkerglen** [comment]
I've confirmed the issue is with `getDrafterState` , it looks like it doesn't handle the first pick in each pack after the first pack.

**Comment by dekkerglen** [comment]
Fixed
