### ISSUE TITLE
Cube failed to update, lists random card as error

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#2024]
From discord:

> Whenever I try to edit mana value I get "Failed to update Chancellor of the Tangle (status undefined)"
> I've tried 5 different cards, same message

http://www.cubecobra.com/cube/list/60bcf52b90fe79103b73c1bb?view=list&page=1

**Comment by dimfish** [comment]
Oh! I wasn't clear enough!

I get a separate error message of the same form, but with the correct card name I tried to edit.

So I tried to edit the mana value of 5 different cards and got "Failed to update CARD (status undefined)" where CARD was the correct card name I was trying to edit.

**Comment by dekkerglen** [comment]
Cannot replicate
