### ISSUE TITLE
Have CSV export enable "Show Unsorted Cards"

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#2033]
From discord:

> When I set my primary sort to "Tag", the export function only exports cards with tags and ignores untagged cards. This is true even if I have the "Show Unsorted Cards" feature enabled so that the display shows my untagged cards. Since my process for building this cube is very tag-centric I'd prefer not to have to change my sort each time I export+import (which is the quickest way for me to add tags) NOTE: This appears to happen in all 4 views (table/list/etc.) but I only tested CSV export

**Comment by tigar** [comment]
I'm a cube cobra user and new to contributing here. Could I take a crack at this as a first issue?

**Comment by ruler501** [comment]
It shouldn't be too hard. Take a look at #2042 since it would be nice to roll it into this.

**Comment by dekkerglen** [comment]
I'd say don't worry about bundling those issues together, although they touch similar code paths. If you need help getting started, please join our discord, and PM me for the contributor role: https://discord.gg/Hn39bCU
