### ISSUE TITLE
Cube Search by Card Returns Same Results

### ISSUE THREAD

**Issue by haganbmj** [dekkerglen/CubeCobra#2034]
**Describe the bug**
Attempting to search using the `card:"name"` syntax on the Cube Search page returns the same 24 results regardless of query or sort direction.

**To Reproduce**

Example Queries. Each returns 24 results, no pagination, same order (note the sort on the second link). Cards are not necessarily even in the returned cubes.
Interestingly, putting an invalid card name will return 0 results.

https://cubecobra.com/search/card:%22Brainstorm%22/0
https://cubecobra.com/search/card:%22Brainstorm%22/0?order=pop
https://cubecobra.com/search/card:%22Bone%20Flute%22/0

**Screenshots**

![image](https://user-images.githubusercontent.com/15820761/121819764-e2428580-cc5c-11eb-958e-7c3514803331.png)

![image](https://user-images.githubusercontent.com/15820761/121819758-db1b7780-cc5c-11eb-9dac-08b1433f0cf0.png)

**Comment by dekkerglen** [comment]
Fixed on master
