### ISSUE TITLE
Have more exports use current sorting

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#2042]
Currently, .txt exports (and I assume other non-csv exports) don't use the current active sorts. CSV does, and we should preserve the sorting to the other exports as well.

**Comment by ruler501** [comment]
We should take this as a chance to refactor the export code. Currently it involves a lot of duplication and I'd like to see that reduced. I'm thinking that most exports could be run through a process like this
```js
const exportToFormat = (res, main, side, sort, format) => {
  main = applySort(main, sort);
  side = applySort(side, sort);
  sections = [['main', applySort(main, sort)], ['side', applySort(side, sort)]];
  for (const [sectionId, sectionCards] of sections) {
    res.write(format.sectionHeader(sectionId));
    res.write('\n');
    for (const card of sectionCards) {
      res.write(format.formatCard(card, sectionId));
      res.write('\n');
    }
    res.write('\n');
  } 
};
```

**Comment by dekkerglen** [comment]
I think what you commented was for deck export, the issue was specifically for cube exports
