### ISSUE TITLE
Duplicate cards with overrides not handled correctly in draft

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#2142]
If I have a cube with multiples of a card, but each with a unique image override, the draft object compresses it so it only keeps one, and then links all copies to that one card, because they share an ID. This makes it so when drafting, all of those duplicates will be the same card, which is incorrect behavior.

We should make sure the override properties are unique for card objects, not counting just the IDs

https://cubecobra.com/cube/overview/slumber

**Comment by lunakv** [comment]
This was solved by #2142 and can be closed.

**Comment by ruler501** [comment]
@lunakv this is 2142 did you mean #2151

**Comment by lunakv** [comment]
yeah. edited
