### ISSUE TITLE
+2 Mace causing issues

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#2145]
he new AFR card name "+2 Mace" is causing some problems in CubeCobra.  First, I notice that the "Paste" option for adding cards didn't like "2x +2 Mace", interpreting it as 4 "Mace" cards.

Next, when trying to quick filter this list (https://cubecobra.com/cube/list/afr-artisan-doubleton) on the word "token", I get the error message:

Invalid regular expression: /+2 Mace/: Nothing to repeat

**Comment by lunakv** [comment]
The second issue is fixed by #2147
