### ISSUE TITLE
Can't update CMC in mass edit view

### ISSUE THREAD

**Issue by vtbassmatt** [dekkerglen/CubeCobra#2157]
**Describe the bug**
I can't edit the CMC of a card from the mass edit view. In the UI, I get the error "Failed to update <cardname> (status undefined)". The POST fails with a 400 and the error message "Failed input validation".

It looks like the frontend (at least on Firefox 90.0.2 on macOS 10.15.7/Intel) is sending `update.cmc` as a string, but the API is expecting a number. I validated this by using Dev Tools to "edit and resend" the request, replacing the string with a number, and it worked.

**To Reproduce**
1. Go to the List tab
2. Click on 'Mass Edit'
3. Alter the CMC of a card

**Expected behavior**
Two issues:
1. The frontend should send the updated CMC as a number, not a string, which would prevent this error entirely.
2. Failing that, the frontend should know where to look in the response for a better error message. "Input failed validation" is more useful than "Status undefined".

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 / Intel
 - Browser: Firefox
 - Version: 90.0.2

**Additional context**

**Comment by vtbassmatt** [comment]
My guess is that something around [here](https://github.com/dekkerglen/CubeCobra/blob/61174b2d6957ad8058efb2cf071b81c637b91f40/src/components/ListView.js#L187) needs to change to recognize that CMC is a number, not a string. But my React game is weak so I'm not going to propose a specific fix.

**Comment by vtbassmatt** [comment]
OK, I couldn't leave it alone, so I poked around until I got this working.

The API contract is confusing -- it expects only a non-negative number. Elsewhere in the codebase, I see that the codebase _really_ expects a non-negative integer or integer plus 0.5. I made the most targeted fix I could imagine, but this might be an area for future broad improvements.

**Comment by lunakv** [comment]
If you're interested, you can include the guards that would force half-integer values as part of #2158.

**Comment by vtbassmatt** [comment]
@lunakv sure, let me see if I can pull that together. And also that guard against `response.json()` not existing.

**Comment by vtbassmatt** [comment]
Bah. I've blown away my Mongo instance. If you're OK with it, I'll omit the changes to force half-integers from this PR. When/if I have time to get my environment going again, I might take another run at it.
