### ISSUE TITLE
"Error, could not add card" (from individual card pages, to a Cube)

### ISSUE THREAD

**Issue by Fereval** [dekkerglen/CubeCobra#2161]
**The bug**
I can't add any cards to a cube **from any individual card pages**.

**To Reproduce**
1. Go to an individual card page (e.g: https://cubecobra.com/tool/card/18ea1434-16c4-4b1a-8728-806360131587)
2. Click on 'Add to Cube....' button (just under the card art)
3. Scroll down to the bottom
4. Click on 'Add'
5. See the red error "Error, could not add card"

**Screenshot and console logs**
![error](https://user-images.githubusercontent.com/17211733/129486624-8e5822c5-3eb8-4452-bffc-883075b42341.jpg)

![console](https://user-images.githubusercontent.com/17211733/129488561-9cc210c5-e7c9-4ef9-808b-6f97594f191a.jpg)

When I click on the last "Add" button the browser console seems to generate this warning:
[cubecobra.com-1629049093674.log](https://github.com/dekkerglen/CubeCobra/files/6988579/cubecobra.com-1629049093674.log)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Chrome Version 92.0.4515.131 (64 bits)

**Additional context**
I just created my account and it is my first time using the site today, maybe I got something wrong?
Thanks!

Adding cards using the "Add/Remove" function in the "List" overview of the cube do work.

_(But this way of adding cards directly from respective card pages is critical for me : as I use foreign language cards, my way to quickly get to them in the Cobra database is first searching for them in Scryfall (recognize foreign card names) which then gives me links to individual Cobra pages. It could be mega nice by the way if one day CC could search for other cards in other languages. :)_

**Comment by lunakv** [comment]
Fixed by #2139, can be closed.
