### ISSUE TITLE
Etched Foil cards removed 

### ISSUE THREAD

**Issue by erikwatson** [dekkerglen/CubeCobra#2169]
Hey all, I don't know if this is the case for all of the etched cards but I noticed today that the etched Approach of the Second Sun had vanished from my cube, suddenly I was down to 359 cards with no warning. 

When re-adding it I noticed that there is no longer an etched version available to select at all. 

It would be nice if Cube Cobra could at least warn us with a notification or something telling us which of our cards have been removed without our knowledge.

**Comment by ruler501** [comment]
Scryfall changed many of the id's for strixhaven mystical archive and since CubeCobra uses that for card lookup that caused the cards to become invalid and get removed automatically.

**Comment by erikwatson** [comment]
> Scryfall changed many of the id's for strixhaven mystical archive and since CubeCobra uses that for card lookup that caused the cards to become invalid and get removed automatically.

Sure, but what I'm saying is that because of that we should have some checks that take place during the data import. If IDs are unstable then we should alert users when an import breaks their things at the very least.

**Comment by dekkerglen** [comment]
Scryfall IDs are supposed to be stable, this is the first time we've had an issue with this dependency.

We do have a pull request open that notifies users when something like this happens, so moving forward if we ever have something like this happen again (unlikely) at least users will be notified.
