### ISSUE TITLE
Cards missing from cube without being removed

### ISSUE THREAD

**Issue by credman0** [dekkerglen/CubeCobra#2173]
**Describe the bug**
Three cards were missing from my cube without being removed.

**To Reproduce**
Don't know, last I remember the cube had 540 cards but today it had 537 cards. Cube is here: https://cubecobra.com/cube/overview/ezg

You can see in the blog when cards were added/removed. The three cards in question are sign in blood, inquisition of kozilek, and cultivate, which were all added about three months ago now but mostly along with other cards that are not missing. They have been re-added now.

**Desktop (please complete the following information):**
Brave browser

**Additional context**
I think I probably would have noticed if the cards were missing the last time I checked, so at the latest that was about 3 weeks ago. Could have happened any time since then. Thanks.

**Comment by lunakv** [comment]
Were those three cards from Strixhaven Mystical Archive? If so, then this is a known one-time data corruption issue that we have no way to fix. See also https://twitter.com/CubeCobra1/status/1434609456147353600

**Comment by credman0** [comment]
Yep, they probably all were. Ok that's no problem thanks for responding. Just wanted to make sure it wasn't an ongoing bug.
