### ISSUE TITLE
Bootstrap migration style issues aggregate issue

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#2227]
This issue is meant to capture all style issues related to the bootstrap migration.

- [ ] Draft preview splits into multiline
- [ ] Block buttons broken

**Comment by dekkerglen** [comment]
- [ ] Button text is wrong

**Comment by dekkerglen** [comment]
- [ ] Buy buttons formatting off
![image](https://user-images.githubusercontent.com/28238025/146657971-63802116-b979-415d-9d28-3ac28433476d.png)

**Comment by dekkerglen** [comment]
- [ ] Loading spinners broken
![image](https://user-images.githubusercontent.com/28238025/146687607-b87f5f7d-f4ec-45b0-b87c-bcef05747986.png)

**Comment by lunakv** [comment]
Would you mind adding screenshots / additional descriptive comments to the issues you found? As is, I don't really even have a grasp of what's wrong, much less how to fix it.
