### ISSUE TITLE
Cube Search by "Popularity" doesn't order correctly

### ISSUE THREAD

**Issue by snfredo** [dekkerglen/CubeCobra#2246]
**Describe the bug**
Cube Search, sorted by "Popularity" returns cubes in an order that doesn't correspond to number of followers.

**To Reproduce**
1. Go to 'Cube' > 'Search Cubes'
2. Enter 'category:"Vintage"' into the Search box
3. Select 'Sorted by Popularity'
5. See error

**Expected behavior**
Cubes should be listed in descending order of number of followers.

**Screenshots**
See attached screenshot, annotated with follower counts from Mar-12-22

**Desktop (please complete the following information):**
Mac OS 11.6, Chrome 99.0.4844.51
<img width="569" alt="Screen Shot 2022-03-12 at 10 28 57 PM" src="https://user-images.githubusercontent.com/12007314/158044103-ffe19b31-ddba-4355-aa7e-d3ade708b0fa.png">

**Comment by dekkerglen** [comment]
Popularity is not measured by followers, it's measured by number of drafts

**Comment by snfredo** [comment]
Interesting. In that case, perhaps # of drafts should not include drafts by the cube's creator?

There are a number of cubes on the first page of results (100cc and 2021 Cooob) where almost all of the drafts are from the cube creator.
