### ISSUE TITLE
Can't export deck after draft. Issue seems to be related to specific card choice in cube?

### ISSUE THREAD

**Issue by Thethifuthus** [dekkerglen/CubeCobra#2248]
When attempting to move to deck building using any feature on [this](https://cubecobra.com/cube/list/old_border) cube, you are instead given the following error message:

`Cannot read property 'push' of undefined
`

This issue has been present since approximately April of 2021, no successful drafts have been made of my cube since this issue arose.

To Reproduce:
Complete any draft of the above cube and upon exporting the choices to the deck builder, the above error is shown.
This behaviour happens even when "have just bots draft" is selected. This issue was found in another cube that was created by cloning my own: see issue [1894](https://github.com/dekkerglen/CubeCobra/issues/1894)

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/102573086/160727463-85b50087-dad5-49b2-899a-b4ac01449681.png">

Problem occurs in both Firefox and Chrome from testing. Have not tested other browsers.

Troubleshooting steps:
- Error persists in cloned versions of the cube, tested by myself, and seen in the above issue 1894. I suspect that the infrequency of the error described in the old man cube (issue 1894) was due to the larger size of the cube causing the offending card(s) not appearing in the draft.
- Error **is not** present when I export the cube as a text and import into a new cube using text only. This is the basis of my assumption that it is a specific card choice in the cube _or_ an issue with the tags, as neither of these features are preserved in a text upload. Test cube where the cards are the default uploaded versions: [Cube recreated with text import](https://cubecobra.com/cube/list/14sl3)
- I systematically removed cards from the cube and replaced them with other cards until the cube was draftable by the bots. See the blog with comments of [cloned cube](https://cubecobra.com/cube/blog/6242986c45ff670fefd1d0dd/0). However, returning the presumed offending cards did not reproduce this behaviour. Removing and readding these cards to the main version of my cube did not fix the issue.
- When bot-only draft is selected, the draft analytics shows only a partial draft is completed by the bots before the error message is received. This is most easily seen in a fresh clone of the cube with a single bot draft attempt.

**Comment by Thethifuthus** [comment]
Update: This issue doesn't seem to affect sealed pool generation - I have tested with several 6x15 pools, and one 15x24 pool (using every card available). Both of these proceed correctly to the deck building process.

However, once again moving from a draft to deck building results in the 
`Cannot read property 'push' of undefined
`
error message.

**Comment by Thethifuthus** [comment]
I suspect this issue persists in the newest version of CubeCobra. I am not longer getting the same error, instead my cube just hangs up at "Finishing up draft..." and never progresses beyond that point.

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/102573086/178634694-4355dd40-c12e-41e4-9d20-230b893d87b8.png">

**Comment by dekkerglen** [comment]
No, this is not the same issue, the system has been completely refractored.

This happens when the draft gets into a bad state and can't be finished at the end of draft, as the result of a bot double picking or something else
