### ISSUE TITLE
Allow Marking Foil/Altered Cards

### ISSUE THREAD

**Issue by purxiz** [dekkerglen/CubeCobra#225]
As a user, I would like to be able to show which cards in my cube are foil and/or altered. This could be accomplished with a simple premium tag, or perhaps more granular options for the type of 'premium' card. I would like these tags to be visible from the cube overview page, perhaps in the form of an icon after or before the card name, like tapped out, or with a subtle highlight of the card name, etc. 

More in general, it would be awesome if we could set icons for tags in general, or set highlighting, etc.

This feature could use the built-in tagging system, and add another menu for how to display tags on the overview page.

**Comment by dekkerglen** [comment]
Note: we've intentionally avoided the term 'pimp' Premium, status, bling are all terms we decided we're ok with.

**Comment by purxiz** [comment]
Sorry! Edited the issue to use 'premium'
