### ISSUE TITLE
Pick by pick breakdown displaying incorrect pack in first pick of 2nd and 3rd packs

### ISSUE THREAD

**Issue by roborocket** [dekkerglen/CubeCobra#2264]
Issue:
Pick by pick breakdown view of saved deck displays incorrect pack information for a given seat for the first picks of second, third, etc. packs. For example, player picks Kitesail Freebooter p2p1, but that pick is described as “Pack 1: Pick 16” below the table of all sequential picks despite being correctly labeled as the first “picked” card of pack 2. 
![DD4A7372-54CF-4AEB-A89B-55BE5F18AD39](https://user-images.githubusercontent.com/59295312/165206381-820b73d9-a322-47e6-affb-2440b9a1eb00.png)
![276C655C-C363-44BA-AD61-447CAA7885F5](https://user-images.githubusercontent.com/59295312/165206386-6e34dea5-52cc-447c-8c62-8ac5f7fbc970.png)

Further the card display generates the 15 cards opened by a different seat for that pack. 

The issue is not present in subsequent picks for the same pack. For example, p2p2 is correctly labeled in the table and below, and the correct 14 card pack for the particular seat is displayed. 

The bug occurs again for p3p1, this time labeled  “Pack 2: Pick 16”, demonstrating the same errors as p2p1, then properly displaying for p3p2 and on. 

Interestingly, the cards for a particular seat in p2p1 are displayed in an apparently random other seat. For example, bot 4’s p2p1 display appears to be the correct pack for the human drafter: https://cubecobra.com/cube/deck/6267410dfb0e8a37f696f613

![1F3D7B2B-79CD-4675-8972-949CFEEB6E7C](https://user-images.githubusercontent.com/59295312/165206443-1fdb0460-c6e1-4def-8303-07cf383f2bbc.png)
![B5CE72E9-2272-4AE5-B186-1089758E46BF](https://user-images.githubusercontent.com/59295312/165206445-d296cf4c-aaa9-4f7e-b89d-f707ab4afb89.png)
![708BD738-5BCF-4939-B9AD-3CAEF2406906](https://user-images.githubusercontent.com/59295312/165206450-cb4d01ae-24f4-4a90-94a5-df68d3231633.png)

Same bug found in other saved decks from the above cube.

Bug found on Chrome for iOS

**Comment by dekkerglen** [comment]
Fixed in master
