### ISSUE TITLE
Multiplayer draft sometimes last pick can be empty and can't recover

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#2279]

**Comment by smartintruesdell** [comment]
Encountered this issue on cubecobradev.com with the following draft:

https://cubecobradev.com/cube/draft/629662b3c3191b7441c87c5f

**Comment by smartintruesdell** [comment]
![image](https://user-images.githubusercontent.com/7267250/171263629-1f602c4b-3cb8-416c-bc82-46391eac928c.png)

**Comment by smartintruesdell** [comment]
Ooh, two in a row.

https://cubecobradev.com/cube/draft/6296644cc3191b7441c87ecf

![image](https://user-images.githubusercontent.com/7267250/171264598-5d616c64-5e3a-4261-b593-3dbc6c075170.png)

**Comment by smartintruesdell** [comment]
3:3. Looks like a reproducible case.

![image](https://user-images.githubusercontent.com/7267250/171265768-f34814ef-57c5-4081-b6ec-5c4584c1b023.png)

**Comment by smartintruesdell** [comment]
I won't touch the cube until you can do research, though here's the csv.

[MartinTruesdell540Development.csv](https://github.com/dekkerglen/CubeCobra/files/8808610/MartinTruesdell540Development.csv)

**Comment by dekkerglen** [comment]
This issue is not cube specific

**Comment by smartintruesdell** [comment]
It doesn't block today, but it's still behaving poorly.

![Screenshot_20220606-192038.png](https://user-images.githubusercontent.com/7267250/172281988-c4fa1039-fbc8-4e96-88ca-d6d5b78d0952.png)

**Comment by smartintruesdell** [comment]
So close! I got through all 45 picks and then hung on Finalizing.

![Screenshot_20220607-193741.png](https://user-images.githubusercontent.com/7267250/172519322-6f874c66-3c09-40be-bff0-3ce5fffdfd09.png)

**Comment by dekkerglen** [comment]
Fixed in master, deployed to dev server
