### ISSUE TITLE
Top cards page shows empty results

### ISSUE THREAD

**Issue by magreenblatt** [dekkerglen/CubeCobra#2318]
**Describe the bug**
The top cards page shows empty results.

**To Reproduce**
1. Browse to https://cubecobra.com/tool/topcards?f=&p=0&s=Elo (or select Cards > Top Cards link from navigation)

**Expected behavior**
A pageable list of top cards should display.

**Screenshots**
![image](https://user-images.githubusercontent.com/413032/185796155-7b8b7e43-432f-4ecd-b710-2a3fd169778f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Google Chrome 104, Firefox 103

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.6.1
 - Browser: Safari

**Additional context**
This seems to have broken or changed recently. It used to work as expected (back in April 2022 at least).

**Comment by austin-schaefer** [comment]
Possibly the same issue as #2302 ?
