### ISSUE TITLE
Bots only pick the first card in the pack

### ISSUE THREAD

**Issue by flomp3r** [dekkerglen/CubeCobra#2321]
Every playtest against bots results in them only picking the the first card at the front of every pack. It happens in my custom drafts, it happens in in my non custom drafts, and it happens if i draft other cubes. The bots don't pick cards based any pattern they just grab the first card available at the front.

**To Reproduce**
-there is no conditions to meet, it just happens every draft, there isn't a playtest for me where it doesn't happen

**Expected behavior**
Bots weren't perfect but they drafted based on some pattern and percieved card elo to my understanding. They don't do that anymore. I can literally tell you what cards will be left in the pack when it comes back around because bots wont pick anything that isnt the first card.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows Ten
 - Browser: Chrome
 - Version: unsure

**Smartphone (please complete the following information):**
 - Device: I dont use cube cobra on mobile

**Comment by awawis** [comment]
I see the same thing; this is likely due to the ELO being stuck at 1200 for everything.

You can see the behavior by clicking through the bots' picks in this example draft: https://cubecobra.com/cube/deck/6352ea235a0c510fb3075975?seat=1&view=picks
