### ISSUE TITLE
Download Draft Decks

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#24]
As a user, I would like to be able to download draft data in a .csv format for me to analyze myself.

**Comment by rudyards** [comment]
Do we want the .csv to be every draft, or one deck at a time?

For every drafts, I'd put it in the "View All" window of Recent Decks, for individual decks I'd just have it available at specific deck pages.

I'm interested in doing this, just wanted clarification before rushing in.
