### ISSUE TITLE
Status dropdown empty in List view

### ISSUE THREAD

**Issue by gustavocs** [dekkerglen/CubeCobra#2404]
**Describe the bug**
Status dropdowns are empty in List view

**To Reproduce**
1. Go to the Cube List tab
2. In **View** dropdown, change from **Table View** to **List View**
4. Check all Status dropdowns with no values

**Expected behavior**
Status dropdown in List View should show current Status and edit as well 

**Screenshots**
![image](https://github.com/dekkerglen/CubeCobra/assets/13592991/5b4f2b86-af5f-450f-bc70-0483471165ef)
![image](https://github.com/dekkerglen/CubeCobra/assets/13592991/25c331fc-fa03-4044-8c36-63bd0344c495)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
- Tested in both Chrome Version 108.0.5359.71 (Official Build) (64-bit) and Firefox 114.0.1 (64-bit)

**Additional context**
This feature worked in the past. Noticed it's been happening maybe for some months

**Comment by ahallaha** [comment]
I'm not set up to run this project locally yet but it looks like the mismatch between "status" and "Status" is causing getLabels to return an empty array.

[Here is where the status dropdown gets populated](https://github.com/dekkerglen/CubeCobra/blob/bbabb088a85adf869499876388b8b54db13ec504/src/components/ListView.js#L117)
[Here is where the status return values should be getting set](https://github.com/dekkerglen/CubeCobra/blob/bbabb088a85adf869499876388b8b54db13ec504/src/utils/Sort.js#L333-L334)
