### ISSUE TITLE
Pressing the Enter Key in the filter field should apply filter

### ISSUE THREAD

**Issue by WesleyM77** [dekkerglen/CubeCobra#2421]
**What would you like to be able to do?**
When typing a filter into the filter field on a cube's list filter tab, pressing "Enter/Return" should apply the filter.

**Describe how you would use the feature**
Saves a bit of time when quickly trying to locate many cards by name (like when I replace proxies with real cards).

**Additional context**
None.

**Comment by Qashworth** [comment]
Hi @dekkerglen! I have a local branch that I believe covers this issue but I'm having some trouble opening a pull request or pushing the branch. When time permits any guidance you can offer would be much appreciated!

**Comment by WesleyM77** [comment]
@Qashworth I believe you push your branch to a forked version of the repo and open the PR on this repo pointing to a branch from your fork.

**Comment by Qashworth** [comment]
@WesleyM77 Thank you so much! That did the trick, I was able to submit.
