### ISSUE TITLE
With Specify Version on, can't add Dandân, Séance, or other special character card names

### ISSUE THREAD

**Issue by adrianbw** [dekkerglen/CubeCobra#2427]
**Describe the bug**
You can't add a card name with a special character if you've selected `Specify Version`, but you can if not:

**To Reproduce**
1. Go to a cube and hit list, then edit
2. Turn on `Specify Version`
3. Type `dandan`
4. Select any version
5. Try to add the card

**Expected behavior**
Dandan is added to the cube.

**Screenshots**
https://github.com/dekkerglen/CubeCobra/assets/12662580/e24d0c28-a471-459a-b844-9a2d41512469

**Desktop (please complete the following information):**
 - macOS
 - Chrome
 - 120.0.6099.109

**Comment by adrianbw** [comment]
I'm working on this.

**Comment by jcaw07** [comment]
Love this!
