### ISSUE TITLE
Encode Search Param

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#255]
Search params need to be encoded to avoid issues with special characters

**Comment by gabyreilly** [comment]
I'll pick up this one as my first ticket!

It seems like there might be a few different issues indicated by this description, I'll try to repro a few cases on the dev server and post them back here. 

But, if there are any specific inputs you have noticed, let me know!

**Comment by gabyreilly** [comment]
Here are the two main issues I see:

![image](https://user-images.githubusercontent.com/18319107/74597855-f8194980-501a-11ea-83fb-304eb6afb73a.png)

![image](https://user-images.githubusercontent.com/18319107/74597860-04050b80-501b-11ea-8817-5d0a3931304c.png)

I'll fix these, and I am open to other scenarios too!
