### ISSUE TITLE
Can't delete cubes

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#260]
Cube removal stopped working with the recent update

**Comment by rudyards** [comment]
Able to replicate this. You can delete a cube by going to Your Profile, clicking on the cube from there, then deleting it, but you can't delete it after creating the cube (it'll claim that the cube is removed, and refresh to the front page, but the cube hasn't been deleted yet).

**Comment by hallc** [comment]
Please assign this to me.
