### ISSUE TITLE
Replace instructional text with tooltips

### ISSUE THREAD

**Issue by emmettbutler** [dekkerglen/CubeCobra#271]
There are a few instances of instructional text in the app, for example the text explaining how the color identity checkboxes work on the mass edit modal. This text takes up too much visual space, making the interface feel cluttered. The text should be put behind a tooltip - only visible when hovering the interface element or tapping a question mark button on mobile.

**Comment by d5c4b3** [comment]
On it

**Comment by GV14982** [comment]
I can work on this.

Do you have a list of places that def need changes? I found the one you mentioned, but I want to get as much of it changed as I can.

**Comment by dekkerglen** [comment]
Too vague of an issue, closing until a more clear example is produced
