### ISSUE TITLE
Compare Cube UI breaks when cubes are very different sizes

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#273]
When comparing a cube with 20 cards to a cube with 700+ cards, the layout of the Compare Cubes screen gets confused
![Screenshot from 2019-09-05 15-43-46](https://user-images.githubusercontent.com/723615/64388500-24548700-cff4-11e9-82ea-43e1fcd04338.png)

This screen should be adjusted to make such large comparisons more usable.

**Comment by phulin** [comment]
Can you check if this still happens? I think the react changes fixed this

**Comment by phulin** [comment]
Ok I don't think this is happening anymore.
