### ISSUE TITLE
Cube popularity rating

### ISSUE THREAD

**Issue by emmettbutler** [dekkerglen/CubeCobra#283]
Github has a "star" feature that indicates when logged-in passerby gave a "+1" to a given repository. This functions as a rough metric of popularity. On Github, a repo's star rating communicates a project's reach and adoption level, which are key factors for developers deciding whether to use the project.

For cubes, the usefulness of such a popularity rating is less clear, since there's no particular reason a user would care about the popularity of a random cube they discover on the site. However, a popularity metric could be a "delighter" feature that creates positive feedback loops in usage behavior, ultimately resulting in increased user acquisition and retention. Emphasis on *could*.

I think this is an interesting idea that warrants some debate.

**Comment by dekkerglen** [comment]
I like it, I want to transition towards a more connected, social platform where users can share cubes, comment on changes (also drafts and any object really), 'follow' cubes to always get notifications for updates etc.

**Comment by dekkerglen** [comment]
Using follower count for popularity
