### ISSUE TITLE
Card Differentiation in Blog Posts

### ISSUE THREAD

**Issue by purxiz** [dekkerglen/CubeCobra#287]
As a user, I'd like it if cards surrounded by [[card markers]] in blog posts could be differentiated rather than showing up in plain text. Preferably, they would show up as a hyperlinks, similar to articles on ChannelFireball or StarCityGames. This might be more practical to do after the planned switch to react.

**Comment by dekkerglen** [comment]
I thought this was an existing issue but I guess I couldn't find. I like the idea of hyperlinks (to tcgplayer w/ affiliate code?), it would be easy to do with the current setup
