### ISSUE TITLE
Unable to upload .csv exported from CubeCobra

### ISSUE THREAD

**Issue by hallc** [dekkerglen/CubeCobra#288]
**Describe the bug**
I cannot upload a .csv file exported from CubeCobra.

**To Reproduce**

Part 1: Export a .csv
1. Navigate to the cube of your choice.
2. Click on the "List" tab.
3. Open the "Export" menu and click on "Comma Separated (.csv)".
4. Save the file to a known location.

Part 2: Import a CubeCobra .csv
1. Log in and create a new cube.
2. Click on the "List" tab.
3. Open the "Bulk Import" menu and click on "Upload File".
4. Choose the .csv exported in part 1 and press "Upload".
5. The upload fails with a 502 Bad Gateway message.

**Expected behavior**
The upload should complete successfully.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Firefox
 - Version: 69.0

**Additional context**

This error occurs on the production server and in the `development` branch.  I haven't tried many cubes, but it does occur for every cube that I have tried.

Error log from my development environment on the `development` branch:

```
cardtree loaded
nameToId loaded
cardimages loaded
full_names loaded
imagedict loaded
carddict loaded
	events.js:186
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.normalizedName (/Users/redacted/Projects/opensource/CubeCobra/serverjs/cards.js:12:37)
    at Object.allIds (/Users/redacted/Projects/opensource/CubeCobra/serverjs/cards.js:13:38)
    at bulkuploadCSV (/Users/redacted/Projects/opensource/CubeCobra/routes/cube_routes.js:992:31)
    at bulkUpload (/Users/redacted/Projects/opensource/CubeCobra/routes/cube_routes.js:1050:7)
    at /Users/redacted/Projects/opensource/CubeCobra/routes/cube_routes.js:969:9
    at /Users/redacted/Projects/opensource/CubeCobra/node_modules/mongoose/lib/model.js:4568:16
    at /Users/redacted/Projects/opensource/CubeCobra/node_modules/mongoose/lib/query.js:4315:12
    at /Users/redacted/Projects/opensource/CubeCobra/node_modules/mongoose/lib/query.js:2797:28
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Emitted 'error' event on Function instance at:
    at /Users/redacted/Projects/opensource/CubeCobra/node_modules/mongoose/lib/model.js:4570:13
    at /Users/redacted/Projects/opensource/CubeCobra/node_modules/mongoose/lib/query.js:4315:12
    at /Users/redacted/Projects/opensource/CubeCobra/node_modules/mongoose/lib/query.js:2797:28
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by dekkerglen** [comment]
Can you link a cube that you know it doesn't work for? Just in case it's a specific card, and not just the entire feature being broken.

**Comment by hallc** [comment]
Here are a few cubes I tried:

https://cubecobra.com/cube/list/gt
https://cubecobra.com/cube/list/modo
https://cubecobra.com/cube/list/wallyscube

It also fails for a cube consisting of a single Giant Growth:
```
Name,CMC,Type,Color,Set,Status,Tags
"Giant Growth",1,"Instant",G,"war",Not Owned,"New"
```
