### ISSUE TITLE
Tags not visible in autocard hovers

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#299]
On the current development branch, hovering a card in the cube view only shows the card image. It should also show the tags for that card if there are any, and the fact that it's not is a regression.

**Comment by emmett9001** [comment]
I can still replicate this issue on current production. Specifically in the visual spoiler view, tags are not visible on autocard hovers. See https://cubecobra.com/cube/list/u3? for an example.

**Comment by lane-eden** [comment]
The tags are also not in hovers in the draft/deckbuilder UI

**Comment by dekkerglen** [comment]
Draft and deckbuilder intentionally don't show tags, it makes sense to view tags when viewing a cube list, but not when you are playtesting

**Comment by phulin** [comment]
This is an easy fix but I don't want to do it twice, so waiting until #391 is merged.

**Comment by emmett9001** [comment]
I can still replicate this on current [dev](http://162.243.163.51/cube/list/e)

**Comment by phulin** [comment]
Just in visual spoiler, right?

**Comment by emmett9001** [comment]
I see working autocard tags on table view, missing autocard tags on visual spoiler, and the list view crashes entirely on current dev.
