### ISSUE TITLE
Scryfall Search Syntax

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#3]
As a user, I would like to be able to use scryfall search syntax to filter my cube. 

Replace the current filter with a text field that will apply the filter when submit is clicked. Have a button labeled 'Advanced Search' that opens up a modal that mimics the advanced search page for scryfall, on submit generate the correct search syntax and pass it into the filter field.

**Comment by emmett9001** [comment]
Currently on the development server, I have to open a new tab to look up what ["Scryfall search syntax"](https://scryfall.com/docs/syntax) is to understand how to filter my cube. I find this a lot less usable than the previous interface, even if it is more powerful.

**Comment by dekkerglen** [comment]
Still w.i.p., see the op regarding advanced modal
