### ISSUE TITLE
Cube total price should use the cheapest non-digital printing of each card

### ISSUE THREAD

**Issue by lane-eden** [dekkerglen/CubeCobra#304]
Currently, if you choose the prerelease foil version of a card for your cube, it counts toward your cube total as the foil price. If you choose a digital-only version of a card, it doesn't count toward the cube total at all.

Instead, we should loop through each printing of each card and select the cheapest, non-digital price to add to the total.

**Comment by purxiz** [comment]
Personally, I would like the total value of my cube to respect foil and special editions pricing.

**Comment by lane-eden** [comment]
The idea of this feature is to give a viewer of the cube a sense of how much it would cost to build that cube themselves.

I agree that are a cube designer it is nice to see the total value of your cube respecting the foil status and card versions you have, so I think we should have this information available to you in the UI as well.

**Comment by purxiz** [comment]
> 
> 
> The idea of this feature is to give a viewer of the cube a sense of how much it would cost to build that cube themselves.
> 
> I agree that are a cube designer it is nice to see the total value of your cube respecting the foil status and card versions you have, so I think we should have this information available to you in the UI as well.

Ah okay, I agree that this should be a feature, as long as we also maintain the pricing of the current card versions in the cube! I didn't think about people wanting to know how much it would be to build the cube!

**Comment by ruler501** [comment]
@dekkerglen I believe this can be closed with the new price code that got merged into master.
