### ISSUE TITLE
Modules/Packages (like cycles but broader)

### ISSUE THREAD

**Issue by mvhsbball22** [dekkerglen/CubeCobra#310]
As a user I would like to be able to create groups of cards that go together in some manner and share those groups with other people -- for example, a group of the "swords", a goblin sacrifice package, or an uncommon graveyard hate package.  

These groups would then show up on a page where users could browse submitted groups and rate them or vote on them or star them (whatever system makes sense site-wide).  These groups should be able to be added to a cube with a single click (like the land cycles). 

Additional features could also include sharing the groups.

The groups could be called packages, modules, groups, or something else.

**Comment by mvhsbball22** [comment]
@purxiz This is the feature request that was mentioned in the #213 comments.

**Comment by dekkerglen** [comment]
I like the name of packages. We could use this as a separate user generated content to supplement cube design. Adding pages to view, browse, and comment would be great.

**Comment by SirManCub** [comment]
Agreed that Packages makes sense since many cube owners have packages that they use in some drafts, but remove or keep separate otherwise. Being able to easily incorporate it into a draft (without having to make a custom draft format) might be nice, too

**Comment by purxiz** [comment]
Although I'm mentioned here, I don't think I"d really like to work on this, so if anyone else is interested feel free to hop in
