### ISSUE TITLE
Put list view mode into the URL as a query param

### ISSUE THREAD

**Issue by lane-eden** [dekkerglen/CubeCobra#317]
As a user, I want to be able to go into Curve View or Visual Spoiler mode and refresh the page or share the link and still be in that mode. Similar to sort and filter, sort the list view mode in the URL for the page.

**Comment by purxiz** [comment]
Check out `buildFilterFromQsArgs()` and `addSearchToUrl()` in `public/js/editcube.js` for a way to do this easily and without affecting other params. See also [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).
