### ISSUE TITLE
Reset "Add Land" modal after closing it. 

### ISSUE THREAD

**Issue by d5c4b3** [dekkerglen/CubeCobra#320]
Having the modal not reset makes me think that I set my land count not add more lands. This causes me to add way too many lands to the deck that I then have to remove. Resetting the modal after saving would prevent this confusion.

**Comment by night-day** [comment]
Is this still an issue?  I tested this and it closed the modal after adding lands.

**Comment by d5c4b3** [comment]
The issue is that when I open the modal again (because I screwed up my land count) it doesn't reset the inputs back to 0.

**Comment by night-day** [comment]
Please assign to me
