### ISSUE TITLE
Copyright Compliance

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#325]
As a site admin, I need to ensure that we are complying with all applicable copyright laws related to linking websites on the site.

Five steps laid out here: https://webmasters.stackexchange.com/questions/16360/user-upload-of-images-copyright-issues
Should be sufficient

**Comment by emmett9001** [comment]
Steps 1, 3, and 5 [here](https://webmasters.stackexchange.com/a/16362) seem only to apply to websites that store images on users' behalf. 2 is easy to add to the terms at the bottom of the site, and 4 seems like a feature:
> Provide a clear way for other site users to flag images as objectionable or potentially violating copyright.
A note in the footer terms about using github or discord to report such violations seems like a fine stopgap.

**Comment by dekkerglen** [comment]
Are we ok closing this issue for now?
