### ISSUE TITLE
Default Version Should Not Be Token

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#343]
There are some cards like 'Ajani's Pridemate' where there exists a token with the same name as a non-token card. If I add this card, and the most recent printing is the token, it will default to the token. 
Similarly to how for the default version we don't allow digital only, we should also not allow token cards.

**Comment by Zenoguy3** [comment]
Addressed in the following pull request
https://github.com/dekkerglen/CubeCobra/pull/368
