### ISSUE TITLE
Filter Syntax Guide

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#367]
As a user, I would like access to a detailed guide for filtering syntax so I can write my own filters.

There is a page + route for it, just the .pug file needs updating. 
Check out a write up of the syntax here (more fields have been added since): https://rentry.co/non4z

**Comment by dekkerglen** [comment]
@omniczech Do you still want me to assign you to this issue?

**Comment by omniczech** [comment]
@dekkerglen sure thing, I've got time

**Comment by emmett9001** [comment]
The syntax guide [on dev](http://162.243.163.51/filters) doesn't look releasable to me.

**Comment by omniczech** [comment]
@emmett9001 working on a cleaner version with the full text
