### ISSUE TITLE
Intermittent missing card images in draft

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#383]
Sometimes, when looking at p1p1 of a draft, some or all of the cards show the cardback image instead of the card's face:

![](https://media.discordapp.net/attachments/619665765997608975/622259868648079380/Screen_Shot_2019-09-13_at_10.38.07_PM.png?width=1081&height=443)

It's unclear how to replicate this error reliably.

**Comment by dekkerglen** [comment]
I'm working on this
