### ISSUE TITLE
Visual spoiler sorts newly added cards to end

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#386]
The visual spoiler sorts my cube by color, then by cmc. However, at the very end of the cube this sort seems to not apply. Instead, cards added after the initial import are all at the end of the spoiler, regardless of their color. I'd like for date added not to be taken into account in the visual spoiler sort.

This appears to be a regression introduced in the 2.1 release, though I'm not certain.

See the very bottom of the visual spoiler view [here](https://cubecobra.com/cube/list/u3) for an example.

**Comment by dekkerglen** [comment]
Could be with the react update, this tab no longer uses the selected sorts and now uses the order of cards stored internally

**Comment by emmett9001** [comment]
Given that this is a regression, I believe it's worth a hotfix between releases.
