### ISSUE TITLE
Multiple Custom Url causes unresponsiveness

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#389]
When adding multiple Custom urls without reloading the page causes the page to become unresponsive.

**Comment by emmett9001** [comment]
What is the specific field you mean by "custom urls"? I'm not sure whether this refers to cube urls or card image urls.

**Comment by dekkerglen** [comment]
Custom image urls

**Comment by dekkerglen** [comment]
Closing this issue, I believe it was due to unrelated server crashes.
