### ISSUE TITLE
Visual spoiler ignores sort

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#390]
Despite the fact that the sort interface is visible in the visual spoiler view, visual spoiler doesn't respond to being sorted in different ways. Either the sort interface should be removed from the visual spoiler view or the view should respond to the sort values changing.

I think this is a regression in the 2.1 release.

**Comment by emmett9001** [comment]
@phulin I notice that list view is still rendered in `editcube.js`, but the other views [are not](https://github.com/dekkerglen/CubeCobra/blob/ffade93b169ef5536741fb3e41050fb3fe094dc6/public/js/editcube.js#L1356-L1363), presumably because the rendering is now handled by React. It looks to me like the previous [sorting approach](https://github.com/dekkerglen/CubeCobra/blob/ffade93b169ef5536741fb3e41050fb3fe094dc6/public/js/editcube.js#L1376) can't be used on these other views without significant changes to the code organization. Can you recommend an approach for adding sort functionality back to the non-list views? Also, I'm curious about the reasoning behind the decision that we no longer want the ability to sort the visual spoiler after the 2.1 release.

**Comment by phulin** [comment]
What's wrong with using sortIntoGroups in the React code? I can look into why this is happening

**Comment by phulin** [comment]
Oh, it looks like I just never re-added the sorting code. So it just needs a slight tweak. I'll make a PR.
