### ISSUE TITLE
Using the /c/ alias for /cube/list deletes url params.

### ISSUE THREAD

**Issue by purxiz** [dekkerglen/CubeCobra#392]
For example, https://cubecobra.com/c/bestcube?f=pow%3E7 will not add the filter, while https://cubecobra.com/cube/list/bestcube?f=pow%3E7 will.

**Comment by lane-eden** [comment]
these seem like completely orthogonal issues unless I am missing some way that this depends on #317. Fixing passing the url params into the /cube/list route shouldn't care what the url params are.

**Comment by purxiz** [comment]
> 
> 
> these seem like completely orthogonal issues unless I am missing some way that #317 depends on this. Fixing passing the url params into the /cube/list route shouldn't care what the url params are.

You're right, didn't think about that, but that's totally correct
