### ISSUE TITLE
unit test coverage

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#395]
The project code should be factored into testable units. Each of these units should have at least one unit test associated with it. These tests should run automatically on each pull request when it's opened or has new commits added, and the results should be visible in GitHub.

This issue cannot be solved in a single pull request. It's meant to track the unit testing effort over the course of multiple pull requests and comments. Feel free to link to this issue when you make a change related to unit testing.

**Comment by purxiz** [comment]
Can you either add a roadmap/progress report, or separate this into multiple issues, so we can assign people as appropriate?

**Comment by emmett9001** [comment]
Splitting this into smaller issues is a great idea, but the reason I haven't already done that is that I'm not entirely sure how to go about it. What are some of the smaller issues you'd like to see related to this? Please open them if you'd like. I wanted to avoid making 20 issues that are all "Write unit tests for the draft code", "Write unit tests for the visualspoiler code", etc. The current untestable state of much of the code makes it hard to know along which lines the unit tests will be divided, since there's a refactoring process that has to happen almost concurrently with the test writing.

**Comment by emmett9001** [comment]
My comment "Feel free to link to this issue when you make a change related to unit testing" is made in the hope that this ticket will become its own progress report over time.

**Comment by emmett9001** [comment]
Pull requests now run the test suite automatically via Travis, and github flags test failures in the PR interface.

**Comment by emmett9001** [comment]
`analytics.js` and the rest of the `cubefn.js` functions are the only pieces of `serverjs` that still don't have tests.
