### ISSUE TITLE
Cube compare not loading the user's show_tag_colors state

### ISSUE THREAD

**Issue by lane-eden** [dekkerglen/CubeCobra#397]
Turn off show tag colors for your account. Compare your cube to another cube. Your tag colors will load showing even though the checkbox is unchecked.

**Comment by phulin** [comment]
Fixed in #408.

**Comment by jamesriley72281** [comment]
@lane-eden On the dev server tag colors are no longer showing at all on the compare lists. Even if you select to see them on that view they still do not display. Let me know if you have any questions or would like me to file a separate issue for this.
