### ISSUE TITLE
Card Kingdom integration

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#403]
As an admin, I want to provide affiliate links for card kingdom in addition to tcgplayer, and provide prices from the respective source.

The prices can be displayed on the buy now button, labeled something like 'buy on tcgplayer for $x.xx'

Contact me for information regarding the CK endpoints.

**Comment by pino-cc** [comment]
As you also have European users, would Cardmarket integration also be possible?
