### ISSUE TITLE
run linter during CI build

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#417]
`js-beautify` style standards can be enforced by having exceptions to the standard cause the CI build to fail.

See [this](https://gist.github.com/ronapelbaum/ef3c3459f01b002d0d719ca205401174) for setup method.

**Comment by phulin** [comment]
very excited to have this set up

**Comment by emmett9001** [comment]
https://github.com/dekkerglen/CubeCobra/pull/412
