### ISSUE TITLE
Multiplayer Drafts

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#42]
As a user, I would like to draft using this website with my friends ahead of time, and then when we meet up we can just pull the cards from the cube for our decks. We wouldn't need to shuffle the cube if we could do this. Just always keep the cube in order and quickly jam out games.

Fair warning: this is a large, difficult feature.

**Comment by KouriR** [comment]
https://github.com/dr4fters/dr4ft works pretty well.

**Comment by dekkerglen** [comment]
Implemented in master
