### ISSUE TITLE
Tags not saving properly

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#432]
According to user reports, it sounds like tags aren't saving correctly. They are being handled correctly client side, but when the page is refreshed the tags are incorrect, suggesting an issue with how we are setting tags server side.

**Comment by phulin** [comment]
I haven't been able to reproduce this, and since there are significant changes to the tagging system in recent updates we should just double check this is working correctly before next release.

**Comment by dekkerglen** [comment]
I was able to reproduce by doing group tags: looks like group tag removing isn't working anywhere, and group tag adding is only happening server side correctly (refresh will show the tags)

**Comment by phulin** [comment]
Still can't reproduce this on current dev, happy to fix if it actually does still exist.

**Comment by dekkerglen** [comment]
It looks like this may have gotten inadvertently fixed, it seems to work fine on dev now.
