### ISSUE TITLE
Custom draft format with filter syntax

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#433]
As a user, I would like to be able to use filter syntax to create my custom draft format. There should be a toggle to turn on the filter syntax, so the existing formats don't break.

**Comment by purxiz** [comment]
Is this preferable to migrating old formats to use the filter syntax? Since they can only use tags, rarity, and * right now (I think), could it be more practical to just change them to rarity:<rarity>, tag:<tag>, or blank for *?

**Comment by dekkerglen** [comment]
Rarity doesn't work currently, it only works for tags, it does support a comma delimited list where it chooses one at random. We could make a one-shot script that revises it accordingly,: `tag="a" or tag="b"`
And also `*` to just empty string
