### ISSUE TITLE
Table sort not working

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#434]
Opening my cube this morning, the lands aren't sorted correctly by colour identity (Chrome, Windows, cube https://cubecobra.com/cube/list/krhom)
If I change the primary sort to something else, then change it back to colour identity, it fixes it until I next press F5.

**Comment by phulin** [comment]
I think this is a regression from the React stuff. I can take a look this afternoon.

**Comment by dekkerglen** [comment]
This was copy/pasted from the bug-reports discord channel. I haven't been able to replicate it.
