### ISSUE TITLE
Suggest Tokens

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#44]
As a user, I would like to be able to easily view what tokens my cube requires.

Add a button in the usercontrols for a cube list that will create a set of token suggestions for the list. These fields need to be added to the card details, scryfall contains this data in the 'all_parts' field: https://scryfall.com/docs/api/cards

**Comment by Balkmeister** [comment]
I got this one.
Can't seem to assign my self here on github though.

**Comment by dekkerglen** [comment]
That's a limitation with GitHub, just comment like you did and I'll get around to assigning you. Bugging me with a link on discord is a good way to, but you still need to comment
