### ISSUE TITLE
Context Modal Broken

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#446]
On development, individual card context modal is broken, does not open, and hides the view.

On 2.1, the context modal doesn't work for lands specifically. Doesn't open modal.

**Comment by dekkerglen** [comment]
This occurs only after the sort is changed

**Comment by dekkerglen** [comment]
Additionally, lands aren't being shown under 'color identity' anymore, I think it's related

**Comment by phulin** [comment]
I think the first issue is now fixed, and the second issue is something weird with that particular cube on the dev server.

**Comment by dekkerglen** [comment]
That's a fresh cube I imported, identical to the list I have on live, and I have the same issue there
