### ISSUE TITLE
sorting on price breaks card preview and editor popup

### ISSUE THREAD

**Issue by Balkmeister** [dekkerglen/CubeCobra#458]
**Describe the bug**
If you sort the cube by price all the card previews when you mouse over a card name disapears. You also do not get the edit card dialog if you click one of the card names. This holds true even if you change the sorting criteria to something else afterwards.

The only way to get back to working previews is to click the "list" tab at the top of the cube frame.

**To Reproduce**
1. Sort your cube by "price"
2. Mouse over any of the card names 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome 
 - Version  76.0.3809.132

**Comment by dekkerglen** [comment]
This is fixed on master
