### ISSUE TITLE
Many duplicate modifications of card.details.display_image

### ISSUE THREAD

**Issue by emmett9001** [dekkerglen/CubeCobra#464]
Modifications of `card.details.display_image` like [this one](https://github.com/dekkerglen/CubeCobra/blob/6a97a206e2d39c5fabb0400b42381093aad04e65/routes/cube_routes.js#L590) are peppered throughout `routes/cube_routes.js`. They are often preceded with [calls to `cardFromId`](https://github.com/dekkerglen/CubeCobra/blob/6a97a206e2d39c5fabb0400b42381093aad04e65/routes/cube_routes.js#L593). This function is nearly identical to [`cardFromId`](https://github.com/dekkerglen/CubeCobra/blob/6a97a206e2d39c5fabb0400b42381093aad04e65/serverjs/cards.js#L13), with the important difference that it does not [set `display_image`](https://github.com/dekkerglen/CubeCobra/blob/6a97a206e2d39c5fabb0400b42381093aad04e65/serverjs/cards.js#L49).

As many modifications of `display_image` as possible should be removed from `cube_routes.js` and replaced with a single modification in [`cardFromId`](https://github.com/dekkerglen/CubeCobra/blob/6a97a206e2d39c5fabb0400b42381093aad04e65/serverjs/cards.js#L13).

**Comment by phulin** [comment]
I feel like this is something we should not be doing with global state and instead just have a function that computes it.
