### ISSUE TITLE
Pack Generation API

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#47]
As a discord bot developer, I would like to have access to an API route for my p1p1 bot.

The specification: 
Returns an array of card names that represents the pack
GET /cube/api/p1p1/:id, where id=cubeID

Code can be recycled from the draft initialization.

**Comment by omnihound** [comment]
Interested in picking this one up.

At any rate, I would suggest a second route

Get /cube/api/p1p1/:id/:seed

So you can always retrieve a given generated pack at any time. The seed number should be returned as part of retrieving the pack initially.
