### ISSUE TITLE
Tags should not be case-sensitive.

### ISSUE THREAD

**Issue by phulin** [dekkerglen/CubeCobra#483]
As a user, tags should autocomplete regardless of their casing. Tags should automatically use the first casing of the tag that a user used. For example, if the user creates the tag "Blue", typing "blu" should still autocomplete to that tag, and typing "blue" and hitting enter should apply the tag "Blue."

**Comment by joshfinnie** [comment]
This is a super interesting topic. Should tags be:

# in the case they were initially submitted
# always uppercase
# always lowercase
# defaulted to uppercase first letters

Is there a default we should abide by?
