### ISSUE TITLE
Bottom border of autocard popup sometimes ends up floating.

### ISSUE THREAD

**Issue by phulin** [dekkerglen/CubeCobra#488]
Usually results when moving the mouse around quickly.

![image](https://user-images.githubusercontent.com/548999/65397888-ab8a5480-dd81-11e9-8018-96ad272940e4.png)

**Comment by phulin** [comment]
In the long term I'd like to replace this with a non-homebrew popup system, but for now we should be able to just fix this bug. I'm a little confused, though, as I can't find any code paths that hide the upper part of the popup without hiding the lower part...

**Comment by dekkerglen** [comment]
I like our 'homebrew' popup system. Gives us more flexibility.

Also, when I first built it, I tried like 4 other image preview libs and none of them worked exactly how I wanted. But... this one does. It was roughly based on another open source project, but I don't remember it off the top of my head.

**Comment by phulin** [comment]
Fair enough, and (as always) not meant as a dig at your work. It does work quite well, and it's good to avoid adding new dependencies to the extent that we can - the webpack bundle sizes are already starting to get a little large. I'll probably just pull all the logic into React at some point to make it easier to understand.

With respect to this particular bug, I weirdly have only been able to reproduce it on Windows. Not sure why that is...
