### ISSUE TITLE
card_faces not populated correctly for DFCs and flip cards

### ISSUE THREAD

**Issue by purxiz** [dekkerglen/CubeCobra#496]
Scryfall API returns a "card_faces" object for dual faced cards. This is necessary to filter on types or oracle text for DFCs, as well as possibly to sort them on certain fields. 

This field is not populated in the card objects, and so can't be used.

**Comment by purxiz** [comment]
The field is an object that contains the Oracle text on each face, as well as types on reverse face. It missing is why dfcs don't show up in filter atm for Oracle search or type on back face.

**Comment by dekkerglen** [comment]
Is the solution to bring in the card faces object, or just append the Oracle text together?

**Comment by purxiz** [comment]
I believe the solution is to bring in card faces. There are other edge cases as well, like loyalty on flip walkers, power and toughness on flip creatures, etc. etc.
