### ISSUE TITLE
Total cube price on Overview page should filter out cards Not Owned

### ISSUE THREAD

**Issue by mdurban** [dekkerglen/CubeCobra#507]
**What would you like to be able to do?**
On the Overview page, where the price is shown as "Approx: $XXXX", that price seems to be computed of _all_ cards in the cube. It would be helpful for this to only show the total cost of all the cards in the cube that you actually own.

**Describe how you would use the feature**
I would love for the place that I use to track my cube to also track up-to-date pricing of all of those cards so I know how much my cube is worth.

**Comment by dekkerglen** [comment]
This should be implemented as a number in addition to the number we currently display. One number shows total value of all cards, the second number shows total value of cards with respect to the card status.
