### ISSUE TITLE
Client-Side Draft Doesn't Save Pick Ratings

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#51]
Since the update to the new draft on the client-side, picks are not being stored in the pick ratings DB. Need to create an extra API route that adds these ratings back in, so the pick ratings can continue to improve. This needs to be called anytime a human makes a pick.

**Comment by lane-eden** [comment]
I'll take this one.

**Comment by lane-eden** [comment]
Fixed in #99
