### ISSUE TITLE
CSV Export Collector's # encoding

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#516]
The collector's number field in csv export has some encoding error. Export a card with a Unicode star  in the collector's #, such as a Japanese war of the spark planeswalker, and then export csv to see the erroneous field.

**Comment by night-day** [comment]
I did a bit of research on this, seems like and Excel issue with how it opens these files.  Opening the CSV in notepad and the star shows up.  

In fact, saving the file again in notepad, and re-opening in Excel, the star shows up!  Very weird, will research some more, or if anyone else has ideas chime in

**Comment by joshfinnie** [comment]
are each of the fields wrapped in quotes? that usually fixes the CSV to excel conversion issues I've had in the past...
