### ISSUE TITLE
Incorrect Automatic Blog Post Titles

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#522]
Blog post titles appear to be empty for at least: simple add/remove, and bulk import only when a correction needs to be made.
![image](https://user-images.githubusercontent.com/28238025/65794388-0501d300-e136-11e9-942e-bd0d5520e9f2.png)

**Comment by night-day** [comment]
Please assign this to me

**Comment by mauriciopasquier** [comment]
Is this fixed in development? I was about to report it. For what it's worth: when adding cards from the list, changing the default title ("Cube Updated – Automatic Post") to anything else doesn't get saved. That is, the post in the posts list (i.e the blog section) appears without title.
