### ISSUE TITLE
Cube API Endpoint

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#543]
In order to allow developers great integration ability, I would like to create a new api endpoint:
/api/cubelist/:id
That returns a plaintext, line break delimited, list of card names.

This would allow dr4ft.info to easily use our cube lists for live drafts.

**Comment by matthewkirby** [comment]
Was this ever merged from the fork? I don't see it in master.

**Comment by dekkerglen** [comment]
Line 2355 of routes/cube_routes.js in branch release-2.7
