### ISSUE TITLE
Top Card Improvements

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#558]
As a user, I would like to see:
- Increased granularity with card ratings, can we do 1 or 2 decimal places?
- A column displaying number of times the card has been picked
- A way to filter by rating, number of times picked

**Comment by phulin** [comment]
I wanted to emphasize that the ratings are approximate and not supposed to be parsed down to the last decimal place, hence only two digits.

**Comment by dekkerglen** [comment]
Fair enough. I still want to see the # of times a card has been picked

**Comment by phulin** [comment]
Yeah for sure!
