### ISSUE TITLE
Page goes blank while using mass edit

### ISSUE THREAD

**Issue by onlywei** [dekkerglen/CubeCobra#560]
**Describe the bug**
I just copied the pauper cube into a new cube, and then I started to try to use the mass edit feature. While using the drop-downs to set certain cards as owned, the entire list suddenly disappears.

**To Reproduce**
1. Create a new cube
2. Import "The Pauper Cube" as txt after exporting it as txt (https://cubecobra.com/cube/overview/5d617ac6c2a85f3b75fe95a4)
3. Switch to list view and click on Mass Edit
4. Start marking cards as owned using the dropdown menus
5. Notice that the list suddenly goes blank after a few uses of the dropdown.

Note that it does not matter whether I am using mouse or keyboard. I tried using just the keyboard to navigate and interact with the form, and I still got the error.

**Expected behavior**
I expect to be able to continue to mass edit my list until I indicate that I am done.

**Screenshots**
I have recorded a video which demonstrates this behavior: https://share.getcloudapp.com/Apuy6q1P

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browse:r Firefox 69.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by dekkerglen** [comment]
Duplicate issue, this is currently fixed on master
