### ISSUE TITLE
Custom Art Upload

### ISSUE THREAD

**Issue by mvhsbball22** [dekkerglen/CubeCobra#57]
As a user, I'd like to be able to upload custom art for individual cards. My cube has significant amounts of alters and digital renders, and it would be nice to share that with people, especially those who might draft in person so they're familiar with the cards.

It probably makes most sense to allow users to upload images near the selection dialog for sets, then populate the drop down with a name the user can provide at time of upload.

**Comment by dekkerglen** [comment]
Applying wontfix for now, because this will require significant upgrades to the server to make it possible.
Currently the hosting budget is too small to support uploading and hosting. We can come back to this issue later on when we have a larger budget, and we are able to accommodate this.

**Comment by mvhsbball22** [comment]
This makes sense as a later thing.  

In the meantime as a stopgap, what about allowing a link to an external hosting service such as imgur?

**Comment by dekkerglen** [comment]
It would still require a large update, but that's definitely doable.

**Comment by emmett9001** [comment]
I'm sketching out a version of this that allows users to provide image urls, sidestepping the issue of image uploading and storage, in https://github.com/dekkerglen/CubeCobra/pull/243

**Comment by emmett9001** [comment]
After chatting with @lane-eden and @purxiz, it sounds like the external URL hosting stopgap mentioned above is worth working on. I've noted some gotchas from our conversation at https://github.com/emmett9001/CubeCobra/pull/4

**Comment by emmett9001** [comment]
@dekkerglen mind assigning me to this issue?

**Comment by emmett9001** [comment]
Was this closed because it was decided not to implement image hosting?
