### ISSUE TITLE
Capitals in Tag Filter Causes no results

### ISSUE THREAD

**Issue by Zenoguy3** [dekkerglen/CubeCobra#584]
**Describe the bug**
It seems that including any capitals in tag filters, including those displayed in the actual tags, causes no results to be returned.

**To Reproduce**
1. Go to List page of any cube with tags
2. Expand Filter dialog
3. Enter any capitalized tag filter, eg: `tag:"New"`
4. See no results returned, even if some cards are tagged "New"

**Expected behavior**
Filters `tag:"New"` and `tag:"new"` should be equivalent and both return all cards tagged "New"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome/Brave

**Comment by night-day** [comment]
Thanks for reporting, this is known bug and is fixed in the next release

See https://github.com/dekkerglen/CubeCobra/issues/546 (that one was for status, but we found and fixed the tag at the same time)
