### ISSUE TITLE
In list groups, don't collapse together cards with 8+ CMC

### ISSUE THREAD

**Issue by phulin** [dekkerglen/CubeCobra#585]
Several users have reported wanting all cards to be broken out by CMC, so that instead of an 8+ CMC section there would be 8, 9, 10, 15, etc.

I assume we did it the other way for a reason; this issue is for discussion.

**Comment by phulin** [comment]
Consensus in Discord discussion was to add a new unlisted sort just for sorting this (e.g. inside the list groups in Table View), but to leave the listed sorts untouched.

**Comment by dekkerglen** [comment]
See how curve view uses an 'unlisted sort' for 'cmc2', and do something similar.
