### ISSUE TITLE
List view - Remove Lands as a column

### ISSUE THREAD

**Issue by narcosis219** [dekkerglen/CubeCobra#60]
As a cube designer, I want to pay close attention to color balance. CubeTutor's list view allows this because "Lands" is not a column, which means that any Lands that have a color identity are slotted under their respective color identity rather than its own section.

An option to disable the "Lands" as a column in list view would be great.

**Comment by lane-eden** [comment]
I believe that if you sort by "Color Identity" rather than "Color Category" you can already do what you are looking for.
