### ISSUE TITLE
Add draft data to cube list view

### ISSUE THREAD

**Issue by omniczech** [dekkerglen/CubeCobra#606]
As a user I'd like to be able to view the same data from "top cards" while in cube views. This might take the form of including the information in the hover popup, or maybe only having it present in the modal pop up.

**Comment by timfreilly** [comment]
Looks like some of this is already done now that ELO is spread everywhere. You can sort by ELO, and ELO is viewable in the individual card modal too. Anything that you'd still want?

**Comment by dekkerglen** [comment]
This has been added
