### ISSUE TITLE
The price in card view disappears when you change version.

### ISSUE THREAD

**Issue by Balkmeister** [dekkerglen/CubeCobra#607]
**Describe the bug**
The box containing price of a card in the card view disapears if you change the version of the card from the drop down.

**To Reproduce**
1. click on any card that have multiple versions
2. click the version selector drop down and select a different version
3. the price displayed below the card image disappears.
**Screenshots**
![image](https://user-images.githubusercontent.com/12525888/66841823-8779f780-ef6a-11e9-9887-559e934e25ca.png)

![image](https://user-images.githubusercontent.com/12525888/66841704-66190b80-ef6a-11e9-9841-d2cce15188b9.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: laptop
 - OS: win 10
 - Browser chrome

**Additional context**

**Comment by anderoonies** [comment]
it appears that `tcgplayer_id` is currently 1-to-1 with card id, and prices are currently looked up by cardID. 

`'/api/getcardfromid/:id'` will need to get cards based on card ID and version (which i think is what the comment "`//need to get the price of the card with the new version in here`" means), i can tackle this as a first issue if it seems reasonable
