### ISSUE TITLE
Incorrect handling of adventure cards causes UI crashes due to lack of colors array.

### ISSUE THREAD

**Issue by phulin** [dekkerglen/CubeCobra#614]
For example, if the scryfall json has no colors array, the UI will crash if that card is included in a cube. Currently an issue on live with Giant Killer. Solution should include better error checking in convertCard

**Comment by dekkerglen** [comment]
The issue is that we're not handling adventure cards correctly, so that the colors array is not being set at all

**Comment by haganbmj** [comment]
Taking a stab at this, but the tests are abysmal to run on Windows so I might just pop open my work Mac tomorrow and see if it's any easier there.
https://github.com/haganbmj/CubeCobra/commit/6ba76022516235f2391f867f2b470652678a34de

As far as I can tell it's a change to `convertColors` and `convertParsedCost`, but the whole updatecards file could really use a rewrite.
