### ISSUE TITLE
Missing tokens

### ISSUE THREAD

**Issue by Balkmeister** [dekkerglen/CubeCobra#630]
Catch all bug report for missing or incorrect token suggestions.
Just comment below if you find more errors.

Missing tokens for card:
Force of rage.

**Comment by dekkerglen** [comment]
Westvale Abbey creatures an invalid token that just shows the card back.

**Comment by dekkerglen** [comment]
Planeswalker emblems are not currently implemented
Earthshaker Khenra grabs copy token instead of it's correct token

**Comment by dekkerglen** [comment]
City's blessing should also be added

**Comment by dekkerglen** [comment]
Not working:
saheeli the gifted makes two different kind of servo tokens?
Vraska makes a treasure as well
and makes pirates
earl of squirrel makes squirrels
gleaming barrier makes a treasure
Tolsimir makes a legendary wolf
call to the feast makes vampire soldiers
chandra flamercaller makes elementals
Kari zev makes a legendary monkey
mist-syndicate naga makes a copy of itself.... is now a just a copy... (not sure if this card has a token)
Regal Caracal and Leonin warleader makes cats
trueheart duelist and adorned pouncer make eternalise tokens
Timely Reinforcements' soldiers
Kalitas, Traitor of Ghet
Serra the benevolent makes an angel

**Comment by emmett9001** [comment]
Tokens don't include command-zone objects that have physical tokens (city's blessing, planeswalker emblems)

**Comment by dekkerglen** [comment]
Monarch, going on an adventure can also be added

**Comment by dekkerglen** [comment]
Trostani's summoner is only pulling up the knight

**Comment by dekkerglen** [comment]
Energy/Poison could be added as well

**Comment by Balkmeister** [comment]
Planewide celebration token not showing up

**Comment by mauriciopasquier** [comment]
- [Blisterpod](https://scryfall.com/card/bfz/163/blisterpod)
