### ISSUE TITLE
Advanced filter toughness misread

### ISSUE THREAD

**Issue by jsmacdonald** [dekkerglen/CubeCobra#656]
Apologize if you'd have preferred this sent via email.  

When using the advanced filter on my cube to sort for cards with toughness <= 2, cards with toughness with 2 digits (10,13,etc) are included in the search.  See results of filtration here:
https://cubecobra.com/cube/list/pseudopowered#f=toughness%3C%3D2

**Comment by purxiz** [comment]
Sending these via github is definitely the way to go! also @dekkerglen this is a good first issue. It's pretty simple. file to check out would be src/util/filter.js. In particular the filterApply function.
