### ISSUE TITLE
Card name reference link broken in followed posts on dashboard [dev]

### ISSUE THREAD

**Issue by RKelln** [dekkerglen/CubeCobra#669]
**Describe the bug**
When I follow a cube [on the dev server] and then go to my dashboard the descriptions of the post show "[[cardname]]" and have no rollover card effect.

**To Reproduce**
1. Log in dev server
2. Follow a cube
3. Go to your dashboard 
4. Check feed

**Expected behavior**
Card names should show card on rollover with no [[ ]] around card name.

**Screenshots**
![Screenshot from 2019-11-07 08-32-28](https://user-images.githubusercontent.com/63819/68393357-df56e900-0139-11ea-85eb-acfe933017f0.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 70

**Comment by RKelln** [comment]
I've tried to figure out what's going on here but it is a mystery to me. I don't know when or how the conversion of [[cardname]] happens.

Note that on the Cube overview page the autolinking works, but not in the comments (in either feed or cube overview):
![Screenshot from 2019-11-07 14-20-04](https://user-images.githubusercontent.com/63819/68420234-e72e8180-0169-11ea-8af1-e609468d3e4d.png)

**Comment by RKelln** [comment]
Actually I think it is a missing `addAutocard(item.html, carddb);` call in the dashboard route. Looking into how to replicate from cube overview but help appreciated.

**Comment by RKelln** [comment]
Ya, by adding:
```
    if (blogs) {
      blogs.forEach(function(item, index) {
        if (!item.date_formatted) {
          item.date_formatted = item.date.toLocaleString("en-US");
        }
        if (item.html) {
          item.html = addAutocard(item.html, carddb);
        }
      });
    }
```
To the dashboard route (plus copy of the import and int from `cube_routes.js` it makes the autocard linking work but couldn't figure out how to do that for comments.
However, this approach seems unwieldy, so perhaps there is a nicer way to handle this?

**Comment by dekkerglen** [comment]
We would have to do it recursively to make it work. The better solution is to add this function to the BlogPost react component, and also the Comment react component, and run all text through there. Then we don't have to recurse through the structure, and we're only calling the function when we need to to

**Comment by RKelln** [comment]
Yup, agreed, fits better at Component level. Perhaps even making a reusable subcomponent TextWIthAutoLinks or whatever that post and comments both use.

**Comment by phulin** [comment]
The problem with filling in the autocards on the client-side is that there won't be enough information to know what card it is - you'd have to pass all that down separately. I think that's why existing code fills it in on the server-side. See the cardHtml function for details

**Comment by dekkerglen** [comment]
We should add a route such as '/cardimage/:name's that reroutes to the appropriate scryfall image
