### ISSUE TITLE
"All Decks" Pagination extends beyond page width

### ISSUE THREAD

**Issue by haganbmj** [dekkerglen/CubeCobra#670]
**Describe the bug**
When too many pages of decks are present the list of pages clips through the page boundary.

**To Reproduce**
1. Navigate to a `/cube/decks/*` page with excess decks.

ex: https://cubecobra.com/cube/decks/modo

<img width="523" alt="decks-pagination" src="https://user-images.githubusercontent.com/15820761/68449669-136fef80-01b6-11ea-8dff-5d2b5a168baa.png">

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Nightly 72.0a1 (2019-11-07) (64-bit)

**Comment by haganbmj** [comment]
As an aside I think this is the first time I've gotten that particular cubes list of decks to load - it does take ~7s though compared to ~1sf or a cube with only a page and a half.

**Comment by dekkerglen** [comment]
The load time issue has been fixed in the current release, but the pagination is logged on issue #600
