### ISSUE TITLE
Deckbuilder authorization checks

### ISSUE THREAD

**Issue by haganbmj** [dekkerglen/CubeCobra#677]
**Describe the bug**
Navigating to `/cube/deckbuilder/:id` is permit for any deck.
Making changes and hitting save works for any Anonymous draft and is rejected for any deck assigned to another user.

**To Reproduce**
1. Navigate to a deck you do not own.
2. Change the url from `/cube/deck/:id` to `/cube/deckbuilder/:id`
3. The resulting `/cube/editdeck/:id` works for Anonymous-owned decks, and returns a 401 for un-owned decks.

**Expected behavior**
Authorization failures would be more reasonable on accessing the deckbuilder page instead of saving deck changes. There's a decent chance that it's just better behavior to combine the two pages and show the deckbuilder when authorized.

**Comment by dekkerglen** [comment]
oh that's a tough one. If we make anonymous decks 401 for deckbuilder, then anon drafts won't be able to build their deck at all. Is that what we want?

**Comment by haganbmj** [comment]
No, you'd probably want anonymous users to have sessions that control which decks they can access within their session.

**Comment by dekkerglen** [comment]
We don't use sessions for anonymous users, using cookies by default opens up a whole new legal can of worms we're not ready for
