### ISSUE TITLE
Card Middle Click

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#68]
As a user, I would like to be able to middle click (or ctrl+click) a card on the list view to navigate towards a card-specific page. 

Use tcgplayer (w/ affiliate link) please. Later on, we can add a new route like '/card/:id' that will pull up a page for the card with information, a buy link, a list of cubes that run this card, etc.

When those list items are clicked, they have an event handler that is intercepts the navigation with e.preventDefault(), the default navigating to '#', we just need to change that URL to the card-specific page. This will only work when middle clicking (or ctrl+click) the item, it won't affect the modal popup.c

**Comment by night-day** [comment]
Please assign this to me, thanks!
