### ISSUE TITLE
Ability to configure explicit seat count for custom draft formats

### ISSUE THREAD

**Issue by GooberRF** [dekkerglen/CubeCobra#685]
I design my cube for 6, 5 pack drafts. When I configure a custom draft format, I can configure the 5 packs fine, however the default "Total Seat" count when starting a draft is still 8. I'd like the ability to default the seat count for my custom draft format to 6.

**Comment by 0nderzeeboot** [comment]
I advised someone to create a custom draft format for 6 players yesterday, thinking this could already be done. They have a 315 card cube designed for 6 players.

**Comment by austin-schaefer** [comment]
Upvote for this one. I usually play my cube with 4 players and it'd be handy to have a setting when configuring a custom draft to set the default seat count.
