### ISSUE TITLE
Table View CSS

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#69]
As a user, I would like the table view to look better.

As mentioned on this podcast (~30m mark): http://solelysingleton.libsyn.com/s6e6-cubetutor-alternatives
There should be tweaks made to the color backgrounds, and the lines in the rowgroups. We need to de-clutter those lines. A good idea is to have rowgroups only have the inner lines separate cards with different CMCs (regardless of primary/secondary sort)

**Comment by dekkerglen** [comment]
Let's also use CSS to force cardnames onto a single line, effectively visually truncating them

**Comment by omniczech** [comment]
Currently working on this one.
