### ISSUE TITLE
Browser displays an empty JSON object when I click on a username

### ISSUE THREAD

**Issue by hallc** [dekkerglen/CubeCobra#697]
# Overview

My browser displays an empty JSON object when I click on a username. 

I've seen the issue on:
* the cube overview screen
* the cube update blog post header
* the explore page
* the play test screen
* the draft deck screen

# Steps to reproduce

1. Navigate to any screen listed above.
2. Click on the username.
3. The browser displays an empty JSON object.

# Expected behavior

I expect to navigate to a screen showing the user's cubes, or a placeholder if that feature has not been implemented.

# Screenshots

Firefox
<img width="945" alt="Firefox" src="https://user-images.githubusercontent.com/1100717/69388230-33171580-0c96-11ea-9b03-7e013435820a.png">

Safari
<img width="946" alt="Safari" src="https://user-images.githubusercontent.com/1100717/69388246-390cf680-0c96-11ea-8a63-2aeeb682ba4a.png">

# Additional information

 - OS: macOS 10.15.1
 - Browser Firefox
 - Version 70.0.1
----

 - OS: macOS 10.15.1
 - Browser Safari
 - Version 13.0.3

**Comment by dekkerglen** [comment]
This occurs if the user is not logged in. I'll work on a fix
