### ISSUE TITLE
Error Pages

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#714]
Several routes have try/catch for error handling (only on async routes).
There are a lot of inconsistencies on how the error handling is done, but we should update all the catch bodies to be:
`
    console.log(err);
    req.flash('danger', err.message);
    res.redirect('/404');`

This way the user has an error message to report, instead of an empty json object that some people get. Additionally, it logs the error in the logs for us to look into later on.

**Comment by phulin** [comment]
I agree in general but error handling in Express is supposed to be done using `next` - that way we can generate custom pages for other error codes too, for instance. See [here](https://gist.github.com/zcaceres/2854ef613751563a3b506fabce4501fd) for example.

**Comment by phulin** [comment]
Also we should use `console.error(err)`, not `console.log`.
