### ISSUE TITLE
& in card names causes issues

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#718]
See kharis & the beholder
This card isn't being processed correctly

**Comment by RKelln** [comment]
I think I can add this to my other changes in updatecards.js. Looking into what this might take to fix.

**Comment by dekkerglen** [comment]
Look for how we handle the '?' from question elemental?

**Comment by RKelln** [comment]
No special handling for '?', but I do have a question about split layout cards:
https://github.com/dekkerglen/CubeCobra/blob/d547235964fb0803d50a2ed6ebbe6c73df9e8c34/serverjs/updatecards.js#L450-L466

Reading this, split cards are supposed to contain the // in their name but other cards with // use the first part unless processed with `isExtra=true`?

(Trying to make some tests for this function that include all the options.)

**Comment by dekkerglen** [comment]
Extras are things like tokens, so you don't have to worry about it being a split card. 

There are special cases for question elemental, but not in that file. It breaks because ? Is a reserved character in url encoding I believe, same as &. We handle it in cube routes and client side is as well

**Comment by RKelln** [comment]
Ah, do you not want to convert html entities when we convert name? Only after it comes out of db?

There also seems to be three sets of normalization going on, one for extra and // cards in `convertName` and then (as well as lowering) in `addCardToCatalog()` to create the `normalizedFullName` and then a `normalizedName` in `cards.js`:

https://github.com/dekkerglen/CubeCobra/blob/6c80188e8e10d2fec3287de626fa415885e1be74/serverjs/cards.js#L120-L125

I would be stoked to DRY this up. My guess is that we can make one `normalizeName(name)` function that can be called in `addCardToCatalog()`  on the full name and the name and remove the normalization in `convertName()`. Then just need to decide if html entities are processed in normalization as well or when pulled out. It is simpler to do in the normalization but not sure what the effects of that would be.

Also, I only see isExtra=true for transform cards:

https://github.com/dekkerglen/CubeCobra/blob/d547235964fb0803d50a2ed6ebbe6c73df9e8c34/serverjs/updatecards.js#L324-L326

**Comment by RKelln** [comment]
Perhaps we want something like this:
```js
normalizeName = (name) => {
return name.trim()
      .normalize('NFD') // convert to consistent unicode escape sequences
      .replace(/[\u0300-\u036f]/g, '')  // remove unicode escape sequences
      // basic html escapes: &, <, >, ', and "
      .replace(/[&<>'"]/g, (tag) => ({'&': '&amp;','<': '&lt;','>': '&gt;',"'": '&#39;','"': '&quot;',}[tag] || tag);
}
card.name = normalizeName(convertName(card, isExtra));
```
Then in `addCardToCatalog()` just:
```js
const nameKey = card.name.toLowerCase();
const fullnameKey = card.full_name.toLowerCase();
```

**Comment by RKelln** [comment]
Note to self: special handling is in name urls generated for api calls. Can use `encodeURIComponent` instead. Have some test code that has this working.

**Comment by RKelln** [comment]
This can be closed.
