### ISSUE TITLE
Double-tapping enter on the Create Cube form produces 2 cubes

### ISSUE THREAD

**Issue by wpr546** [dekkerglen/CubeCobra#742]
**Describe the bug**
If you hit [enter] twice on the Create Cube form, you get 2 cubes with the same name

**To Reproduce**
1. Sign in, click on your username in the upper-right
2. Click on 'Create New Cube'
3. Fill out some name
4. Hit [enter] twice
5. Go back to your profile and observer that there are two cubes created

**Expected behavior**
One cube with the entered name will get created

**Screenshots**
![image](https://user-images.githubusercontent.com/17842975/70577078-4d3e6800-1b5f-11ea-9c0f-21f75deebbad.png)

![image](https://user-images.githubusercontent.com/17842975/70577100-57606680-1b5f-11ea-8b66-5758605fa12b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 78.0.3904.108 (Official Build) (64-bit) (cohort: Stable)

**Comment by dekkerglen** [comment]
We can fix this with the waiting button component, but that would require moving the entire layout into react.
