### ISSUE TITLE
Color Tags

### ISSUE THREAD

**Issue by lane-eden** [dekkerglen/CubeCobra#75]
As a user, I would like to be able to choose a color for each of my tags. This could work by clicking on an existing tag and selecting a color from a palette in a dropdown.

**Comment by dekkerglen** [comment]
I think the best way to implement this would be to add an item in the user controls toolbar labeled 'Tag Colors', that opens up a modal where the user can set the tag colors for the cube. Save it in a dict on the cube db object with an API call or a post form submission.

**Comment by lane-eden** [comment]
added in #308
