### ISSUE TITLE
Provide the ability to hide the 'Add Basic Lands' option as a custom draft format option

### ISSUE THREAD

**Issue by klaffke** [dekkerglen/CubeCobra#751]
Most draft formats are designed to be drafted with an arbitrary number of basic lands at the players' disposal. But there are Cubes where basic lands are part of the cube itself (they are drafted like any other card).

Here, for example, is the desert cube:

https://www.reddit.com/r/magicTCG/comments/28vrdk/the_desert_cube_most_flavorful_cube_ever_created/

I'd like to have a way to disable the 'Add Basic Lands' option for custom draft formats in CubeCobra.

**Comment by RKelln** [comment]
I'll take a look at adding this to my custom draft changes.

**Comment by dekkerglen** [comment]
This is now solved with the customization of basic lands
