### ISSUE TITLE
Cube Card Count on List view on mobile

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#778]
On mobile, I would like to easily be able to see the cube one-line description from the list view, so I don't have to go to the overview to see it.

**Comment by timfreilly** [comment]
Looks like it's specifically being hidden at mobile size:

<img width="710" alt="Screen Shot 2020-02-20 at 4 46 58 PM" src="https://user-images.githubusercontent.com/1253274/74993692-a8fb5c00-5400-11ea-94a2-33d9fc7b1931.png">

Do we figure that should just be undone?
