### ISSUE TITLE
Mobile List view Zoom Out

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#779]
List view of a cube in mobile mode makes me scroll horizontally now to see the whole cube. I guess that's an improvement, but it'd feel a lot better if I could zoom out further so I could see more than two columns.

**Comment by phulin** [comment]
I honestly don't understand what people are trying to see by zooming out on mobile. Next time someone brings this up can we ask them? You can't see anything if the table is any smaller than it is right now...

**Comment by dekkerglen** [comment]
DrRuler had shown us CT's list view in portrait mode, and you can see all the columns, and you can still read all the cards. I don't like it, but it technically works
