### ISSUE TITLE
Compare Cubes feature broken in 2.8

### ISSUE THREAD

**Issue by KouriR** [dekkerglen/CubeCobra#793]
When I compare cubes, the page loads but the comparison table does not appear.
Examples:
https://cubecobra.com/cube/compare/1uj/to/opterown
https://cubecobra.com/cube/compare/oy/to/krhom

OS: Windows 10
Browsers tested: Edge build 18363, Chrome 79.0.3945.88

Source view shows cube data is there but it's not rendering for some reason.

**Comment by dekkerglen** [comment]
Fixed
