### ISSUE TITLE
Saving Changes to Cube Overview fails to render next page

### ISSUE THREAD

**Issue by haganbmj** [dekkerglen/CubeCobra#797]
**Describe the bug**
Clicking Save Changes while editing the Cube Overview is intended to redirect back to the overview page, but fails to render the page.

**To Reproduce**
1. Click "Edit Overview" on your cube.
2. Click "Save Changes".
3. Page redirects to an unrendered overview page.

```
Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

**Screenshots**
<img width="879" alt="overview-save-changes" src="https://user-images.githubusercontent.com/15820761/71770110-2291c600-2ef7-11ea-865f-21b7250c4be1.png">

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Firefox Nightly 73.0a1 (2020-01-02) (64-bit)

**Comment by phulin** [comment]
I haven't been able to reproduce this - is it still happening?

**Comment by dekkerglen** [comment]
Not sure. I couldn't repro it but figured it's something with the fields changed

**Comment by haganbmj** [comment]
Yeah still happens. I can reproduce it on my overview by just opening the Edit Overview modal and clicking Save Changes - no edits necessary.

<img width="609" alt="edit-overview1" src="https://user-images.githubusercontent.com/15820761/71776545-7cc77100-2f61-11ea-917d-cb0d670aa080.png">
<img width="605" alt="edit-overview2" src="https://user-images.githubusercontent.com/15820761/71776547-7cc77100-2f61-11ea-961b-c39a2afc4c43.png">

**Comment by dekkerglen** [comment]
No errors in the console?

**Comment by dekkerglen** [comment]
I believe this has been inadvertently fixed
