### ISSUE TITLE
Delete/Edit Draft Decks

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#8]
As a user, I would like to be able to delete and edit my draft decks.

Add user controls when viewing a draft deck only when the owner of that draft deck is viewing. If the owner is anonymous, never show those controls. Add 'Edit Deck' and redirect to the deckbuilder, and 'Delete Deck' which performs the ajax delete on a delete cube route, similar to delete cube or delete blog post.

**Comment by SirManCub** [comment]
Would this include things like naming the deck, adding a description and/or comments, etc?

**Comment by dekkerglen** [comment]
We could lump naming and description with this, but I would stay away from commenting until we start on the site-wide social functions

**Comment by bkopleck** [comment]
Seconding name and description fields, would also like to be able to see the rest of the pool when not the deck owner (for Wishes, Arcane Savant, etc).
