### ISSUE TITLE
Remove/Replace behavior not working as expected.

### ISSUE THREAD

**Issue by OtherwiseJunk** [dekkerglen/CubeCobra#804]
**Describe the bug**
I attempted to use the remove replace functionality, but it seems like some of the cards I removed are still in the list, even though the cube card count didn't change and I see some of the new cards I added.

https://cubecobra.com/cube/list/2pf

**To Reproduce**
1. Go to cube list.
2. Click Add/Remove
3. Add some pairs of cards to remove/replace
4. Notice that the new list has all of the cards you intended to add, but that other cards are missing instead of the ones you indicated should be removed.

**Expected behavior**
The cards indicated are removed and replaced with the new cards as specified.

**Screenshots**

https://Dart.s-ul.eu/w7YG4Gvw
https://Dart.s-ul.eu/LLB7VfLg
https://Dart.s-ul.eu/u7BM2pcC
https://Dart.s-ul.eu/fdlEP1rE

In the example provided, Blaze seems to have been correctly replaced with fireball.
https://Dart.s-ul.eu/E2VEWNAp

**Desktop (please complete the following information):**
Windows 10
Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Additional Context**
Is there any way to revert actions like these? I'm really worried random cards have dropped out and ruined my list since the card count is the same, but the newly added cards are appearing in the list with the cards they're supposed to have replaced.

https://cubecobra.com/cube/compare/2pf/to/63f
(I just compared the cube to an uneditted import, and it looks like Captain's Hook, Rampant Growth, Kodama's Reach, Vampire Aristocrat, and Syncopate were removed instead of Opt, Last Gasp, Disdainful Stroke, Cnacel, and Naturalize being removed)

**Comment by dekkerglen** [comment]
Issuing hotfix now

**Comment by OtherwiseJunk** [comment]
wow that was incredibly fast. Nice!
