### ISSUE TITLE
Incorrect sorting behavior for mana rocks.

### ISSUE THREAD

**Issue by d5c4b3** [dekkerglen/CubeCobra#83]
This might be intended behavior, but I don't think so.

**Describe the bug**
Signets/Talismans count as multicolored cards for Color Category sort. Lands are not incorrectly categorized this way. Badlands only shows under Rakdos for Color Identity. 

**To Reproduce**
Add a rakdos signet to a cube.

**Expected behavior**
The signet should count as an artifact when sorting by Color Category.

**Comment by dekkerglen** [comment]
This issue happens when secondary sort is types multicolor, rakdos is sorted into the guild instead of type because of this
