### ISSUE TITLE
Card modal sizings on mobile

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#848]
Some controls on the card modal on mobile don't scale right.
Take notice to buttons, and the color picker

![Screenshot_20200113-114241_Chrome](https://user-images.githubusercontent.com/28238025/72274337-f4e50500-35f9-11ea-92c9-87a63c29e49f.jpg)

**Comment by phulin** [comment]
I made all the buttons' text shorter but then you added more buttons

**Comment by dekkerglen** [comment]
¯\_(ツ)_/¯
definitely my fault
