### ISSUE TITLE
Add 'Proxied' as card status

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#849]
Add a new card status: 'Proxied'

**Comment by apantel** [comment]
As a user who uses proxies, would this be different from "not owned"?

**Comment by dekkerglen** [comment]
I think so, I use not owned for cards I want but don't have yet, then switch to ordered, and owned. Proxied is a bit different

**Comment by roborocket** [comment]
I'd like to try this as a first issue. Any suggestions on where to start? Still not too familiar with the organization of the code.
