### ISSUE TITLE
Add EDH/Commander to Cube Types

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#866]
Add EDH/Commander to cube type override.

this needs to be updated in the cube overview edit modal, but also in the form submit route, as there is validation done there on valid types

**Comment by timfreilly** [comment]
Is this different from the selection on Edit Overview?
<img width="197" alt="Screen Shot 2020-02-15 at 8 49 11 PM" src="https://user-images.githubusercontent.com/1253274/74599319-aaa9d600-5034-11ea-9771-6e2587175215.png">
