### ISSUE TITLE
.CSV Uploaded Cards Image Display Issue

### ISSUE THREAD

**Issue by jamesriley72281** [dekkerglen/CubeCobra#883]
**Describe the bug**
When uploading a deck via .CSV card images are only displaying the default_card.png image of the card back. There isn't any errors showing in the console or network tab of dev tools. 

See screenshot attached. The two images that did load were from manually added cards.

**To Reproduce**
1. Go to a cube list
2. Import another cube list from .csv

**Expected behavior**
Cards would upload to the cube list, including their images
**Actual**
Card information is uploaded, but the card image does not display

**Screenshots**
![imageissue](https://user-images.githubusercontent.com/22227186/72498507-2675f000-37f5-11ea-8fac-953cce6b6206.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Link to the cube I was working with the issue : https://www.codecobradev.com/cube/list/6mu#view=spoiler

**Comment by phulin** [comment]
All the imgUrls are getting set to the stirng "undefined" as a result of some issue in the upload code.

**Comment by ruler501** [comment]
I'll take this up since this was my change.
