### ISSUE TITLE
Use github.com/RyanSaxe/MagicDraftBot as draft backend

### ISSUE THREAD

**Issue by viccuad** [dekkerglen/CubeCobra#884]
Hello,
Thanks for cubecobra, it's awesome :).

**What would you like to be able to do?**

Improve drafting by using https://github.com/RyanSaxe/MagicDraftBot as backend.
(See https://draftsim.com/ , https://draftsim.com/ryan-saxe-bot-model/)

**Describe how you would use the feature**

Talk to the author and see if he is willing to license his work as, for example, AGPL, which would suit cubecobra.com and protect his current unlicensed work from used for profit by other people without contributing back. He can always double-license it with a privative license if he wants so sell his work.

**Comment by dekkerglen** [comment]
Ryan Saxe is already working with us, this model will not work for cube do to the large card pool.
