### ISSUE TITLE
CMC ≥ 17 Not Showing In List View

### ISSUE THREAD

**Issue by jamesriley72281** [dekkerglen/CubeCobra#888]
**Describe the bug**
If you manually adjust a CMC to be greater than 17 the Table view will now show the card. The card is still counted in the cube and can be seen in other views. If you switch to sort by CMC the 8+ column will include the card in it's total, but the card name is not listed

**To Reproduce**
1. Go to list view and sort by CMC
2. Click on card
3. Set CMC to be 17 or above

**Expected behavior**
Card would move to the 8+ cmc column and still be displayed under the header count

**Screenshots**
<img width="488" alt="Screen Shot 2020-01-16 at 11 13 49 AM" src="https://user-images.githubusercontent.com/22227186/72546981-5f43b280-3851-11ea-9ad8-bb064b9b96e9.png">

**Desktop (please complete the following information):**

**Comment by phulin** [comment]
Interesting. I wrote the code this way because I didn't expect anyone to ever want CMC>16, and there are no cards with CMC>16 aside from Gleemax. Can you explain what you're trying to do? That will inform how we fix this

**Comment by jamesriley72281** [comment]
I was just testing this section of the application and when testing I will often try different out of normal things. I don't think anyone would need this at this this time, but could cause an issue MTG decides to ever print a large cmc card above 16 or if someone just makes a typo and can't see there card. Could possible put a check to not allow over 16 now, but may cause issues if mtg ever gets wild with CMC in the future.
