### ISSUE TITLE
Changing filters in list view causes crash

### ISSUE THREAD

**Issue by apantel** [dekkerglen/CubeCobra#898]
**Describe the bug**
Sometimes, changing filters when in list view causes the "Something went wrong" error message.

**To Reproduce**
1. Open the page in table view.
2. Set a filter that excludes some cards.
3. Change to list view.
4. Change to a filter that includes some cards that the prior one excluded.
5. "Something went wrong" shows up

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome

**Comment by dekkerglen** [comment]
Is this on live server or dev server?

**Comment by apantel** [comment]
Live

**Comment by RKelln** [comment]
Confirmed on live and test. Some sort of react error in client:

tags is undefined

From:
```js
const TagInput = ({ tags, addTag, deleteTag, reorderTag, ...props }) => (
  <TagContext.Consumer>
    {({ allSuggestions, addSuggestion, tagColorClass }) => (
      <ReactTags
        tags={tags.map((tag) => ({ ...tag, className: tagColorClass(tag.text) }))}
```
