### ISSUE TITLE
Improve Card List Item Background Colors

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#901]
Background colors for card list items in table view need a bit of work. 

For example, red/land and black/colorless need a bit more contrast

![image](https://user-images.githubusercontent.com/28238025/72640681-5f69ae00-3936-11ea-84d3-b90a83d7e3bb.png)
![image](https://user-images.githubusercontent.com/28238025/72640686-61cc0800-3936-11ea-8aed-ed0c282aacf7.png)

**Comment by vhaso** [comment]
Hello Gwen,
new guy here. I would like to make a contribution to the project. 
Could I take this as my first issue?
Cheers,
Klaas-Jan

**Comment by dekkerglen** [comment]
Go for it! :)
I encourage you to join the discord server here: https://discord.gg/YBetzMD
Just @dekkaru there, and I'll give you access to the developer channels. That's where we do the majority of discussion.
