### ISSUE TITLE
Edit custom format loads incorrect state

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#920]
When I went to edit my ELD custom draft format, the radio button for set draft/cube draft was incorrectly set:

![image](https://user-images.githubusercontent.com/28238025/72667194-1de50b80-39e7-11ea-9c78-771010ef048c.png)

**Comment by mawills** [comment]
taking a look at this one.

**Comment by dekkerglen** [comment]
Sorry I didn't see your comment, I had already fixed it
