### ISSUE TITLE
CSS Text-Align Issue

### ISSUE THREAD

**Issue by jamesriley72281** [dekkerglen/CubeCobra#97]
**Describe the bug**
The development branch currently has in issue with the `card-body` under Cube Overview. The H6 heading tag is aligning text to the center incorrectly.

**To Reproduce**
1. Load the development branch
2. Navigate to cube overview

**Expected behavior**
Cube type and creator will both be aligned the same

**Screenshots**
<img width="957" alt="text-align" src="https://user-images.githubusercontent.com/22227186/63231375-61d9a780-c1e0-11e9-9666-fb3486fe6e20.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by omniczech** [comment]
I'll tackle this
