### ISSUE TITLE
Treat Art Cards as Alternate Printings

### ISSUE THREAD

**Issue by devonrichardsz** [dekkerglen/CubeCobra#976]
**What would you like to be able to do?**
I'd like the art cards in my cube to work as printings of the cards for sorting and analytics. 

**Describe how you would use the feature**
This allows me to treat them as if they were just another card. 

**Additional context**
May relate to #970

**Comment by dekkerglen** [comment]
They do work, you can add them to your cube

**Comment by ruler501** [comment]
I haven't tested this but I don't think they'd show up as the same card when doing cube comparisons and don't auto populate all the card fields for sorts and analytics.
